#issue-1074 Added image selecting/highlighting when clicking on the grey area or license label
magento/adobe-stock-integration pull request #1082
Opened 2020-03-31 13:48 UTC by serhiyzhovnir

### Description (*)

This PR adds Media Gallery image item selecting/highlighting styles when clicking or hovering grey area or a license label.
![1074](https://user-images.githubusercontent.com/31502344/78031009-9a8f5100-736b-11ea-9a75-30e9dc127d20.gif)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1074: The image is not selected/highlighted when clicking on it's grey area

### Manual testing scenarios (*)

1. From Admin go to Content - Pages, click Add New Page
2. Expand Content, click Show / Hide Editor, click Insert Image...
3. Try to select an image by clicking on its grey area

2020-04-01 15:43 UTC, VladimirZaets requested changes
Hi @serhiyzhovnir. Thanks for collaboration. Please take a look at my comment below

2020-04-01 15:43 UTC, VladimirZaets commented on MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
> +             click="function(){ if (!$collapsible.opened()) {select($row())} }" >
Can you please move this function from view to model method? It's not good to have some logic in html template. thanks

2020-04-04 11:04 UTC, sivaschenko commented
Also, I think that we should not select images on hover, only on click

2020-04-04 13:35 UTC, serhiyzhovnir commented
Hi @VladimirZaets @sivaschenko 
The requested changes were added.
Please, check this PR again.
Thank you!

2020-04-14 10:25 UTC, sivaschenko approved these changes

2020-04-14 10:25 UTC, merged