[MFTF] Cover #708
magento/adobe-stock-integration pull request #1093
Opened 2020-04-01 09:43 UTC by engcom-Charlie

### Description (*)

- cover https://github.com/magento/adobe-stock-integration/issues/708
- fixed issue with absent `Licensed` label on image.

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#708: [MFTF] User views limited image information from the image grid in Media Gallery
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-01 20:27 UTC, engcom-Charlie commented
@magento run all tests

2020-04-02 11:45 UTC, sivaschenko requested changes
Thanks for the PR @engcom-Charlie ! Please see my review comments

2020-04-02 11:45 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImageInformationGridAssertActionGroup.xml
> +<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Please move this action group to MediaGalleryUi module

2020-04-02 11:45 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockNewMediaGalleryDeleteImageActionGroup.xml
> +    <actionGroup name="AdminAdobeStockNewMediaGalleryDeleteImageActionGroup">
Please move this action group to MediaGalleryUi module

2020-04-06 10:52 UTC, engcom-Charlie commented
the test will be passed after merge https://github.com/magento/adobe-stock-integration/pull/1129

2020-05-12 14:23 UTC, gabrieldagama commented
Closing this PR since the test cases are also covered here:
https://github.com/magento/adobe-stock-integration/pull/1334

2020-05-12 14:23 UTC, closed without merging