fix #1095
magento/adobe-stock-integration pull request #1100
Opened 2020-04-01 15:38 UTC by engcom-Charlie

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1095: Image "Type" information is not available in Details page
2. ...

### Manual testing scenarios (*)

Please see https://github.com/magento/adobe-stock-integration/issues/1095

2020-04-01 20:27 UTC, engcom-Charlie commented
@magento run all tests

2020-04-02 11:56 UTC, sivaschenko requested changes
Thanks for the pull request @engcom-Charlie ! Please take a look at my review comments

2020-04-02 11:56 UTC, sivaschenko commented on AdobeStockImage/etc/db_schema.xml
> +        <column xsi:type="int" name="media_type_id" padding="10" unsigned="true" nullable="false" identity="false" default="0" comment="Media Type Id"/>
There is no need to add the media_type_id to the grid. This attribute is not displayed in the grid, only in the image details panel

2020-04-02 11:56 UTC, sivaschenko commented on MediaGalleryUi/Model/GetImageDetailsByAssetId.php
> +                    'value' => $this->getTypeImageByMediaTypeId($mediaTypeId),
Please retrieve the type from the contenty_type field of the media_gallery_asset.

If the asset comes from Adobe Stock (there is information stored in adobe_stock_asset) - please update this information in `\Magento\AdobeStockImageAdminUi\Plugin\AddAdobeStockImageDetailsPlugin`

2020-04-03 11:42 UTC, sivaschenko approved these changes

2020-04-04 11:06 UTC, merged