Issue 1028 - Fixed issue with asset license info loading
magento/adobe-stock-integration pull request #1129
Opened 2020-04-04 11:20 UTC by gabrieldagama

### Description (*)
The problem was happening when you open AdobeStock gallery and images that were licensed weren't having the label being displayed. 

The problem existed because we were listening to the data provider to fetch licensed information from backend, but when we were building the request we were getting information from the masonry component instead of the data provider. Some times it worked probably because of timing.

Just changed the approach, so now we are listening to the data provider and fetching the items from the data provider.

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1028: Adobe Stock asset license information is fetched for the previous page while paging navigation

### Manual testing scenarios (*)
1. Follow the steps on the issue. From a user perspective, we were loading the AdobeStock grid and not having the licensed labels on the licensed images.

2020-04-04 12:40 UTC, sivaschenko requested changes
Thanks for the pull request @gabrieldagama ! Please see my comment regarding the naming

Can you please also check if the change is fixing https://github.com/magento/adobe-stock-integration/issues/1106 and mention it in the description if does

2020-04-04 12:40 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
> +        isUserNotAuthorized: function() {
I'd prefer to revert the function to have a better naming
```suggestion
        isUserAuthorized: function() {
```

2020-04-04 12:40 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
> +        loginEventUpdateLicensed: function() {
```suggestion
        handleUserUpdate: function() {
```

2020-04-04 12:40 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
> +        itemsEventUpdateLicensed: function(items) {
```suggestion
        handleItemsUpdate: function(items) {
```

2020-04-07 18:51 UTC, VladimirZaets approved these changes

2020-04-09 13:56 UTC, sivaschenko commented
@magento run Functional Tests B2B

2020-04-09 16:29 UTC, sivaschenko approved these changes

2020-04-09 16:29 UTC, merged