1147: rename AssetIndexer and move indexer logic to another module
magento/adobe-stock-integration pull request #1157
Opened 2020-04-07 12:07 UTC by coderimus

#621 # Description (*)
This PR provides changes requested in the #1147 
Main changes:
- represent 2 new modules `Magento_MediaGallerySynchronization` and `Magento_MediaGallerySynchronizationApi`
- extract sync logic to those modules

### Fixed Issues (if relevant)
#1147 

### Manual testing scenarios (*)
N/A

2020-04-09 17:20 UTC, coderimus commented
@sivaschenko @lenaorobei 
As I can see this PR https://github.com/magento/adobe-stock-integration/pull/1158 keeps the `ExcludedDirectories`  under the `MediaGalleryUi` If this is a decision, this current PR depends on the mentioned one.

2020-04-15 11:57 UTC, sivaschenko requested changes
Thanks for the pull request @coderimus ! Please take a look at my review comments

2020-04-15 11:57 UTC, sivaschenko commented on AdobeStockImage/Model/AssetIndexer.php
> +class AssetIndexer implements AssetImagesSynchronizationInterface
I think this class can be removed as asset's grid was eliminated

2020-04-15 11:57 UTC, sivaschenko commented on MediaGallerySynchronization/Model/AssetImagesSynchronization.php
> +class AssetImagesSynchronization implements AssetImagesSynchronizationInterface
Let's simplify the name of the class and interface
```suggestion
class ImagesSynchronization implements ImagesSynchronizationInterface
```

2020-04-15 11:57 UTC, sivaschenko commented on MediaGallerySynchronization/Model/AssetImagesSynchronization.php
>      public function execute(\SplFileInfo $item): void
Please change the method to work with multiple `$items` (\SplFileInfo[])
```suggestion
    public function execute(array $items): void
```

2020-04-15 11:57 UTC, sivaschenko commented on MediaGalleryUi/composer.json
> +        "magento/module-media-gallery-synchronization-api": "*",
I don't think MediaGalleryUi should depend on synchronization, please reverse the dependency

2020-04-17 10:30 UTC, sivaschenko approved these changes

2020-04-18 10:09 UTC, sivaschenko commented
Functional Tests B2B failure is not related to changes and randomly failing on other PRs as well: `Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest`

MHI failure is related to the protected method that was extended

2020-04-18 10:11 UTC, merged