License an image from the Media Gallery
magento/adobe-stock-integration pull request #1160
Opened 2020-04-07 12:49 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#910: License an image from the Media Gallery
2. ...

 Manual testing scenarios (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)
2. Have a preview image saved from Adobe Stock
3. Have Adobe Stock account with credits - contact @sivaschenko 

Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)
3. Open the menu for the preview image saved from Adobe Stock

"License" option is present in the image menu. Selecting the option initiates the images licensing process

2020-04-07 19:28 UTC, VladimirZaets requested changes
Hi @Nazar65. Please take a look at my comments below

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +                title: 'License',
Maybe we need to translate the title?

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +                        message = 'There was an error on attempt to get the image details.';
The same here, it should be translated

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +
Remove empty line

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +                return parseInt(record.licensed, 16) === 0  ? true  : false;
you can just return "parseInt(record.licensed, 16) === 0" it will be boolean automatically

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +            this._super().observe(['visible']);
Use initObsorvable method to set new observable variables

2020-04-07 19:28 UTC, VladimirZaets commented on AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
> +                    $.ajaxSetup({
I am not sure that change global ajax configuration is the best solution. I understand that you need to make requests synchronously, but the best solution, in this case, is to make a refactoring of a method that sends requests and gives the ability to receive ajax configuration.

2020-04-08 08:17 UTC, Nazar65 commented
Hi @VladimirZaets thank you for review, now it looks much better

2020-04-14 13:39 UTC, VladimirZaets approved these changes

2020-04-15 00:38 UTC, merged