The folders structure is not updated after deleting, the focus remains on deleted folder
magento/adobe-stock-integration pull request #1165
Opened 2020-04-08 07:10 UTC by engcom-Charlie

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#888: The folders structure is not updated after deleting, the focus remains on deleted folder
2. ...

### Manual testing scenarios (*)

See https://github.com/magento/adobe-stock-integration/issues/888

2020-04-08 09:50 UTC, Nazar65 requested changes

2020-04-08 09:50 UTC, Nazar65 commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
> +                var activeNode = this.getMageMediaBrowserData().activeNode;
all variables must be declared in the top of method, please use
```
             var activeNodePath,
                 activeNode;
```

2020-04-09 18:29 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-04-14 10:46 UTC, sivaschenko approved these changes

2020-04-14 10:46 UTC, merged