magento/adobe-stock-integration#1146: Eliminate grid index and use as…
magento/adobe-stock-integration pull request #1175
Opened 2020-04-08 22:02 UTC by sidolov

…sets table instead.

### Description (*)

### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration#1146: Move index table from MediaGalleryUi module to MediaGalleryIndexer

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-09 05:49 UTC, Nazar65 requested changes

2020-04-09 05:49 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
> -        <column name="directory">
I wonder if directiryTree filter will work afrer remiwing this column ?

2020-04-09 15:33 UTC, lenaorobei commented
Looks like we need to remove `\Magento\AdobeStockImage\Model\SetLicensedInMediaGalleryGrid` with all the usages.

This table is also used -> `AdobeStockImage/etc/db_schema.xml` and `AdobeStockImage/etc/db_schema_whitelist.json`.

2020-04-14 11:01 UTC, sivaschenko commented
@magento run Unit Tests

2020-04-14 11:01 UTC, sivaschenko commented
@magento run Functional Tests EE

2020-04-14 12:15 UTC, sivaschenko commented
Unit tests are green: http://10.234.235.163:8080/job/Unit-Tests/934/

2020-04-14 12:49 UTC, sivaschenko commented
@magento run Functional Tests EE

2020-04-14 12:54 UTC, sivaschenko commented
Functional Tests EE build: http://10.234.229.78:8080/job/Functional-Tests-EE/1876/

2020-04-14 14:38 UTC, sivaschenko commented
Functional Tests EE build is green

2020-04-14 14:51 UTC, sivaschenko commented
Tests: https://m2build-comm.devops.magento.com/job/MTS-API-Tests/8784/

2020-04-15 00:38 UTC, merged