[MFTF] Cover #1119, #1120
magento/adobe-stock-integration pull request #1184
Opened 2020-04-10 08:09 UTC by engcom-Charlie

### Description (*)

Cover #1119, #1120

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1119: Cover deleting folder from Standalone Media Gallery
2. magento/adobe-stock-integration#1120: User creates a new folder in Standalone Media Gallery

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-12 20:31 UTC, coderimus commented on MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryCreateDeleteFolderTest.xml
> +            <group value="adobe_stock_integration"/>
Should it be an `adobe_stock_integration` group? Maybe, a `media_gallery_ui` group should be introduced where we can group tests for the MediaGalleryUi module.

2020-04-14 11:13 UTC, sivaschenko requested changes
Thanks for the pull request @engcom-Charlie ! Please ensure there are no mentions of adobe stock in the media gallery modules. Introduce a separate test suite for media gallery tests

2020-04-14 21:31 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2020-04-15 11:34 UTC, sivaschenko approved these changes

2020-04-15 11:36 UTC, merged