Sorting options are incomplete
magento/adobe-stock-integration pull request #1230
Opened 2020-04-17 11:09 UTC by engcom-Charlie

### Description (*)

Closes #1190

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1190: Sorting options are incomplete
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-18 18:56 UTC, engcom-Charlie commented
@magento run Functional Tests EE

2020-04-20 11:19 UTC, sivaschenko requested changes
Thanks for the pull request @engcom-Charlie ! Please see my review comments

2020-04-20 11:19 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/sortBy.js
> +                        this.options.push({
Is it possible to provide these options from XML configuration of the sorting component?

2020-04-21 04:44 UTC, VladimirZaets submitted a review, later dismissed

2020-04-21 12:08 UTC, sivaschenko requested changes
Thanks for the PR @engcom-Charlie , can you please fix the static tests

2020-04-21 13:38 UTC, chalov-anton requested changes
The default _Sort by_ is empty 
![sort_by_empty](https://user-images.githubusercontent.com/45624059/79872440-507f1580-83d5-11ea-81be-6e4a1a8b2bcd.png)
Please, change it to _Newest First_ to be the default

2020-04-21 14:46 UTC, engcom-Charlie commented
@chalov-anton Please check this issue now.

2020-04-22 07:39 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

2020-04-22 14:04 UTC, lenaorobei commented
@magento run Functional Tests CE, Functional Tests B2B

2020-04-22 18:17 UTC, lenaorobei commented
https://m2build-ur.devops.magento.com/view/all/job/All-User-Requested-Tests/31818/

2020-04-23 15:03 UTC, lenaorobei commented
@magento run all tests

2020-04-23 17:56 UTC, lenaorobei commented
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

2020-04-23 18:36 UTC, lenaorobei commented
@magento run Unit Tests

2020-04-24 01:53 UTC, merged