An image remains selected when switching between folders
magento/adobe-stock-integration pull request #1231
Opened 2020-04-17 12:41 UTC by engcom-Charlie

### Description (*)

Closes #1117 

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1117: An image remains selected when switching between folders
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-17 13:34 UTC, Nazar65 requested changes

2020-04-17 13:34 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
> +            mediaGalleryDirectoryComponent: '${ $.ns }.${ $.ns }.media_gallery_directories',
It would be better to move name space to xml configuration

2020-04-17 13:36 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
> +            mediaGalleryDirectoryComponent: '${ $.ns }.${ $.ns }.media_gallery_directories',
https://github.com/magento/adobe-stock-integration/blob/36b8d15c61f168969aa39a1e8539cd20a24cf902/MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml#L178

2020-04-18 06:06 UTC, engcom-Charlie commented
@magento run Unit tests

2020-04-18 06:06 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2020-04-20 11:12 UTC, sivaschenko approved these changes

2020-04-21 21:51 UTC, lenaorobei commented
Please address unit tests failures

2020-04-22 11:47 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

The image is deselected after switching to another folder 

![image deselected_2020-04-22 14-44](https://user-images.githubusercontent.com/45624059/79978164-1cc0f000-84a8-11ea-8c62-60d0ce08d585.gif)

2020-04-22 18:08 UTC, merged