"The image cannot be located" message appears if Save Preview when there are more than one page in Media Gallery
magento/adobe-stock-integration pull request #1259
Opened 2020-04-22 13:23 UTC by engcom-Charlie

### Description (*)

Closes #1254

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1254: "The image cannot be located" message appears if Save Preview when there are more than one page in Media Gallery 
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-23 07:58 UTC, engcom-Charlie commented
It needs to recheck after merge https://github.com/magento/adobe-stock-integration/pull/1230

2020-04-24 17:19 UTC, Nazar65 requested changes

2020-04-24 17:19 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
> +                    this.sortBy().selectDefaultOption();
In this case if we upload for example 10 images, this operation will  be executed 10 time's

2020-04-24 17:22 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
> +                    this.sortBy().selectDefaultOption();
I would recommend to move this operation to stop method to run this on last uploaded image

2020-04-27 16:28 UTC, lenaorobei requested changes
Please adjust code with changes from https://github.com/magento/adobe-stock-integration/pull/1275

2020-04-28 10:19 UTC, sivaschenko submitted a review, later dismissed

2020-04-28 11:51 UTC, chalov-anton requested changes
@engcom-Charlie Please, add behaviour when a selected image from Media Gallery is not deselected after Uploading a new image 
![uploade_deselect](https://user-images.githubusercontent.com/45624059/80483915-8be28c80-895f-11ea-8bb0-6e135f467030.gif)

2020-04-28 12:15 UTC, sivaschenko approved these changes

2020-04-28 12:25 UTC, chalov-anton reviewed
:heavy_check_mark: QA Passed

2020-04-28 21:49 UTC, merged