Media gallery synchronization does not remove obsolete images from database
magento/adobe-stock-integration pull request #1264
Opened 2020-04-23 10:26 UTC by engcom-Charlie

### Description (*)

Closes #1261

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1261: Media gallery synchronization does not remove obsolete images from database
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-04-23 10:58 UTC, sivaschenko requested changes
Thanks for the pull request @engcom-Charlie ! Please take a look at my comment

2020-04-23 10:58 UTC, sivaschenko commented on MediaGallerySynchronization/Model/Synchronize.php
> +        $this->resolveNonExistedAssets->execute($assetsPaths);
Can you please introduce this operation in an instance of `SynchronizeFilesInterface` added to synchronizers pool. And utilize `\Magento\MediaGalleryApi\Api\DeleteAssetsByPathsInterface` for removing assets

2020-04-24 08:02 UTC, sivaschenko approved these changes

2020-04-24 08:04 UTC, sivaschenko requested changes
Thanks for updates @engcom-Charlie ! Please see my review suggestions

2020-04-24 08:04 UTC, sivaschenko commented on MediaGallerySynchronization/Model/Synchronize.php
> +        return substr($assetPath, strlen($this->getMediaDirectory()->getAbsolutePath()));
```suggestion
        return $this->getMediaDirectory()->getRelativePath($assetPath);
```

2020-04-24 08:04 UTC, sivaschenko commented on MediaGallerySynchronization/Model/Synchronize.php
> +            $assetsPaths[] = $relativePath === $item->getFilename() ? '/' . $relativePath : $relativePath;
I think it would be good to move this code to `getRelativePath` private method

2020-04-26 19:47 UTC, sivaschenko approved these changes

2020-04-27 10:16 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2020-04-27 11:25 UTC, sivaschenko commented
@magento run Unit tests

2020-04-27 11:26 UTC, sivaschenko commented
@magento run Functional Tests EE

2020-04-28 10:03 UTC, merged