1245: fix image still exists after delete
magento/adobe-stock-integration pull request #1279
Opened 2020-04-26 12:13 UTC by coderimus

### Description (*)
To fix the reported issue I provide this PR: use `Magento\Cms\Model\Wysiwyg\Images\Storage::deleteFile` for image delete process. This method removes the image physically and has a plugin which will remove data from a data storage - `\Magento\MediaGallery\Plugin\Wysiwyg\Images\Storage::afterDeleteFile` I also choose this method because of `Magento_MediaGalleryUi` has a dependency and use the `Magento_CMS module`.

**NOTE**
This PR has a dependency on [#27994](https://github.com/magento/magento2/pull/27994)

### Fixed Issues (if relevant)
#1245 

### Manual testing scenarios (*)
Described in #1245

2020-04-26 19:17 UTC, sivaschenko requested changes
Thanks for the pull request, @coderimus ! please see my comment

2020-04-26 19:17 UTC, sivaschenko commented on MediaGalleryUi/Model/DeleteImage.php
> +        $absolutePath = $mediaDirectory->getAbsolutePath($asset->getPath());
Please check if the path is blacklisted before deleting an image (`IsPathBlacklistedInterface`).
Also, please add the information that the asset is removed from the database via the plugin

2020-04-26 19:22 UTC, sivaschenko commented
@coderimus does this pull request depends on https://github.com/magento/magento2/pull/27994 ? Or what is the dependency?

2020-04-26 19:31 UTC, coderimus commented
@sivaschenko thank you for your review!
At the beginning of working on this PR, I faced with the issue I thought made those 2 PR related. But I was wrong. Dependencies removed.

2020-04-26 20:04 UTC, sivaschenko submitted a review, later dismissed

2020-04-27 09:01 UTC, engcom-Bravo requested changes
:x: QA Failed

Now the behavior is opposite, the image is deleted from ```pub/media``` but, as I understand, it is not deleted from the database. As a result - broken images are displayed on Media Gallery grig
![1245_2020-04-27](https://user-images.githubusercontent.com/51680745/80353959-c45e6980-887e-11ea-9635-9edab95b997c.gif)

2020-04-27 09:17 UTC, coderimus commented
@engcom-Bravo thank you for the QA. May I asked you to make one more test: as I can see you added an image to the root directory and I faced with the same behaviour as you but could reproduce it only several times and than it was gone. Thought that it was my local problem.

Test scenario: add an image to any kind of folder except root media directory and then test delete it. 

Thank you

2020-04-27 09:44 UTC, coderimus commented
@sivaschenko I would like to request your expertise :) Yesterday when I made this PR [magento/magento2#27994](https://github.com/magento/magento2/pull/27994) I faced with an issue which I considered as my local. But it appears to be the real one according to the current PR QA result.

Steps to reproduce: add an image to the root media gallery folder. It's path should be `/download.jpg` for example. After that try to delete it. The result will be next: image deleted, an entry in the  `media_content_asset` still exists.

I found that the reason for this is that the `$path` [variable here](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/MediaGallery/Model/ResourceModel/DeleteAssetsByPaths.php#L51) equals to the image name without `/` for cases as I described before.

I tried to fix it like on my screenshot and it seems to be work but I am not totally sure that this is the correct way. Please, check this.

![image](https://user-images.githubusercontent.com/5318512/80358273-d0e5c080-8884-11ea-8753-a2fc0b022271.png)

2020-04-27 13:00 UTC, sivaschenko commented
@coderimus I don't think the path should be changed in the delete service, the correct path should be passed by client

2020-04-28 06:43 UTC, Nazar65 commented
:heavy_check_mark: QA Passed  images deleted from physical storage, folder deleted from physical storage and from the media_gallery_asset
**Note** Tested with linked PR on Magento 2 https://github.com/magento/magento2/pull/27994

2020-04-28 21:49 UTC, merged