[MFTF] Cover adding Category image via WYSIWYG from Enhanced Media Gallery
magento/adobe-stock-integration pull request #1360
Opened 2020-05-18 10:31 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1073: Cover adding Category image via WYSIWYG from Enhanced Media Gallery
2. ...

### Manual testing scenarios (*)
All tests green :heavy_check_mark:

2020-05-18 13:16 UTC, Nazar65 commented
@magento run all tests

2020-05-18 19:06 UTC, Nazar65 commented
@magento run all tests

2020-05-18 19:14 UTC, Nazar65 commented
@magento run all tests

2020-05-18 19:18 UTC, Nazar65 commented
@magento run all tests

2020-05-18 19:30 UTC, Nazar65 commented
@magento run all tests

2020-05-19 06:29 UTC, Nazar65 commented
@magento run all tests

2020-05-19 10:49 UTC, Nazar65 commented
@magento run all tests

2020-05-20 16:29 UTC, Nazar65 commented
@magento run all tests

2020-05-21 12:07 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! There are few minor changes required

2020-05-21 12:07 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryAddCategoryImageTest.xml
> +        <actionGroup ref="AdminAdobeStockImagePreviewConditionalCloseActionGroup" stepKey="closePreviewIfOpened"/>
The condition click was moved to AdminAdobeStockExpandImagePreviewActionGroup - AdminAdobeStockImagePreviewConditionalCloseActionGroup action group can be removed

2020-05-21 12:07 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImagePreviewConditionalCloseActionGroup.xml
> +<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
The condition click was moved to AdminAdobeStockExpandImagePreviewActionGroup - AdminAdobeStockImagePreviewConditionalCloseActionGroup action group can be removed

2020-05-21 12:07 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/Section/AdminMediaGalleryHeaderButtonsSection.xml
> +        <element name="imageInGrid" type="button" selector="//img[contains(@src, '{{imageName}}')]" parameterized="true"/>
Please move this element to AdminEnhancedMediaGalleryImageActionsSection

2020-05-21 12:55 UTC, gabrieldagama approved these changes

2020-05-21 13:36 UTC, Nazar65 commented
@magento run all tests

2020-05-22 09:09 UTC, merged