Replicate old media gallery behavior with current tree path
magento/adobe-stock-integration pull request #1385
Opened 2020-05-25 07:31 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1382: The "catalog/category" and "wysiwyg" directories are not created if Enhanced Media Gallery is enabled
2. ...

### Manual testing scenarios (*)
1. Create a **clean** Magento installation with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Go to _Stores - Configuration - Advanced -System - Enhanced Media Gallery_ and select **Enabled - Yes**
4. Perform ```bin/magento media-gallery:sync``` and ```bin/magento cache:clean```

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Verify that there are no _/wysiwyg_ and _Catalog/category_ Directories
3. Go to **Catalog - Categories**
4. Click **Select from Gallery** button and verify if _Catalog/category_ Directory appeared in folder tree

2020-05-25 07:32 UTC, Nazar65 commented
@magento run all tests

2020-05-25 07:51 UTC, Nazar65 commented
@magento run all tests

2020-05-25 08:22 UTC, Nazar65 commented
@magento run all tests

2020-05-25 08:53 UTC, Nazar65 commented
@magento run all tests

2020-05-26 08:44 UTC, gabrieldagama commented
Hi @Nazar65, thanks for the PR, please follow some considerations below:

I believe the GetTree action should still be just a HttpGetActionInterface, and not implement HttpPostActionInterface. The main objective here is to GetTree and we shouldn't be creating folders, after discussing with @sivaschenko we agreed that a preferred solution would be to:

- Not change the GetTree action and handle the problem on the frontend.
- To avoid overcomplicating the frontend we believe it would be better to handle that on `directoryTree` initialization, by introducing a folder creation request (we already have the endpoint for that) whenever the currentTreePath param exists, if the folder already exists, the request won't do anything and when this request is done we will run `getJsonTree` that will fetch the recently created folder with the tree.

2020-05-26 08:44 UTC, gabrieldagama requested changes
Hi @Nazar65, thanks for the PR, please follow some considerations below:

I believe the GetTree action should still be just a HttpGetActionInterface, and not implement HttpPostActionInterface. The main objective here is to GetTree and we shouldn't be creating folders, after discussing with @sivaschenko we agreed that a preferred solution would be to:

- Not change the GetTree action and handle the problem on the frontend.
- To avoid overcomplicating the frontend we believe it would be better to handle that on `directoryTree` initialization, by introducing a folder creation request (we already have the endpoint for that) whenever the currentTreePath param exists, if the folder already exists, the request won't do anything and when this request is done we will run `getJsonTree` that will fetch the recently created folder with the tree.

2020-05-26 13:52 UTC, Nazar65 commented
@magento run all tests

2020-05-26 13:53 UTC, Nazar65 commented
@gabrieldagama could you please review new changes ?

2020-05-26 14:02 UTC, Nazar65 commented
@magento run all tests

2020-05-26 19:56 UTC, Nazar65 commented
@magento run all tests

2020-05-27 07:37 UTC, Nazar65 commented
@magento run all tests

2020-05-27 07:45 UTC, Nazar65 commented
@magento run all tests

2020-05-27 13:07 UTC, gabrieldagama requested changes
Hi @Nazar65 thanks for your changes, it looks great! Please follow some thoughts below.

2020-05-27 13:07 UTC, gabrieldagama commented on MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
> +                            var selectedFolder = _.isUndefined(this.selectedFolder()) ||
I think we can create a function to return the new folder path, it will be easier to understand than the ternary conditions here.

2020-05-27 13:07 UTC, gabrieldagama commented on MediaGalleryUi/view/adminhtml/web/js/directory/createDirectory.js
> +    return function (createFolderUrl, paths) {
I like the approach of isolating these API calls, nice work! I would just put then inside the actions folder.

2020-05-27 14:04 UTC, Nazar65 commented
@magento run all tests

2020-05-27 14:59 UTC, Nazar65 commented
@magento run all tests

2020-05-28 06:46 UTC, Nazar65 commented
@magento run all test

2020-05-28 06:47 UTC, Nazar65 commented
@magento run all tests

2020-05-28 13:46 UTC, Nazar65 commented
@magento run all tests

2020-05-29 07:04 UTC, Nazar65 commented
@magento Functional Tests CE

2020-05-29 07:05 UTC, Nazar65 commented
@magento run all tests

2020-06-01 08:02 UTC, Nazar65 commented
@magento run all tests

2020-06-02 11:09 UTC, Nazar65 commented
@magento run Functional Tests B2B,  Functional Tests CE, Functional Tests EE

2020-06-03 13:22 UTC, sivaschenko submitted a review, later dismissed

2020-06-03 13:55 UTC, chalov-anton requested changes
❌ QA Failed

The folder creation and selection is correct. But when the Media Galley Is opened, a _Failed to load resource: the server responded with a status of 400 (Bad Request)_ error message appears in dev console 
![400_bad_request](https://user-images.githubusercontent.com/45624059/83645334-09329a00-a5bb-11ea-9212-d01401fb7020.png)

2020-06-03 17:18 UTC, sivaschenko commented
@chalov-anton thanks for the verification, please create an issue for this problem for the next milestone

@Nazar65 thanks for the updates, please fix the functional tests

2020-06-04 09:22 UTC, chalov-anton commented
> @chalov-anton thanks for the verification, please create an issue for this problem for the next milestone
> 
> @Nazar65 thanks for the updates, please fix the functional tests

:heavy_check_mark: Done

2020-06-04 12:12 UTC, sivaschenko commented
@magento run all tests

2020-06-04 12:19 UTC, gabrieldagama submitted a review, later dismissed

2020-06-04 12:34 UTC, chalov-anton commented
✔️ QA Passed
1) If the Enhanced Media Gallery is disabled in _Srores - Configuration_
![emg_en_no](https://user-images.githubusercontent.com/45624059/83756838-490b8700-a678-11ea-80ae-d4eb93344007.png)
It is not available from _Content_
![emg_content_no](https://user-images.githubusercontent.com/45624059/83757080-9f78c580-a678-11ea-8cd4-b939e5f1eeb6.png)

2) Folder Creation work as expected

2020-06-04 14:23 UTC, sivaschenko commented
@magento run all tests

2020-06-04 16:08 UTC, sivaschenko approved these changes

2020-06-04 16:09 UTC, merged