[MFTF] Removed dependency of Media Gallery tests on ASI
magento/adobe-stock-integration pull request #1389
Opened 2020-05-26 10:17 UTC by gabrieldagama

### Description (*)

Removed dependency of Media Gallery tests on ASI

2020-05-26 10:17 UTC, gabrieldagama commented
@magento run all tests

2020-05-26 11:00 UTC, sivaschenko requested changes
Thanks for the pull request @gabrieldagama ! Please see my review comments

2020-05-26 11:00 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryClickImageInGridActionGroup.xml
> +            <argument name="imageName" type="string" defaultValue=""/>
Should we just remove the defaultValue in this case?

2020-05-26 12:55 UTC, gabrieldagama commented
@magento run all tests

2020-05-28 11:52 UTC, sivaschenko approved these changes

2020-05-28 11:53 UTC, merged