[MFTF] Cover with MFTF filtering by Source media gallery
magento/adobe-stock-integration pull request #1402
Opened 2020-06-01 09:55 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1393: [MFTF] Cover filtering by Source
2. ...

### Manual testing scenarios (*)
N/A MFTF MediaGallery suites all Green :heavy_check_mark:

2020-06-01 09:55 UTC, Nazar65 commented
@magento run all tests

2020-06-01 14:52 UTC, Nazar65 commented
@magenti run all tests

2020-06-01 14:54 UTC, Nazar65 commented
@magento run all tests

2020-06-02 12:10 UTC, gabrieldagama requested changes
Hi @Nazar65, thanks for your pull request, it looks great! Please follow some small typos and camel case suggestions.

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGallerySelectSourceFilterActionGroup.xml
> +            <description>Select Soucce filter by provided option</description>
```suggestion
            <description>Select source filter by provided option</description>
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertImageNotExistsInTheGridActionGroup.xml
> +            <description>Asserts that image not exists in media gallery grid</description>
```suggestion
            <description>Asserts that image does not exists in media gallery grid</description>
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryFilterImagesBySourceTest.xml
> +        <actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openStandAloneMediaGalleryPage"/>
```suggestion
        <actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openStandaloneMediaGalleryPage"/>
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryFilterImagesBySourceTest.xml
> +        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="ApplyLocalFilter">
```suggestion
        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="applyLocalFilter">
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryFilterImagesBySourceTest.xml
> +        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="ApplyAdobeStockFilter">
```suggestion
        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="applyAdobeStockFilter">
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGallerySaveFiltersStateTest.xml
> +        <actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openStandAloneMediaGalleryPage"/>
```suggestion
        <actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openStandaloneMediaGalleryPage"/>
```

2020-06-02 12:10 UTC, gabrieldagama commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGallerySaveFiltersStateTest.xml
> +        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="ApplyLocalFilter">
```suggestion
        <actionGroup ref="AdminEnhancedMediaGallerySelectSourceFilterActionGroup" stepKey="applyLocalFilter">
```

2020-06-02 16:16 UTC, Nazar65 commented
@magento run all tests

2020-06-03 08:58 UTC, gabrieldagama approved these changes

2020-06-03 12:40 UTC, merged