#1410 - Update images after folder deletion
magento/adobe-stock-integration pull request #1413
Opened 2020-06-04 17:09 UTC by gabrieldagama

### Description (*)

Added an event to folder deletion function, extended the masonry grid, and added the reloadGrid method, I believe it is better to components to handle their own state so the suggestion here is to use events instead of injecting parent components to children.

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1410: If the Root is not empty, the image state is not updated when the containing folder has been deleted.

### Manual testing scenarios (*)

1. Go to **Content** -> **Media Gallery**
2. Do not select any folder from the folder tree
3. Save an image Preview or Upload an image
4. Create a new folder named 1 for example
5. Select the previously created folder and Sava Preview in it or Upload an image
6. Delete the Previously created folder
7. Create a new folder with the same name (1)
8. Select the created folder.

The image that was previously added to folder 1 should not be there anymore.

2020-06-04 17:13 UTC, gabrieldagama commented
@magento run all tests

2020-06-05 08:34 UTC, gabrieldagama commented
@magento run all tests

2020-06-05 08:42 UTC, gabrieldagama commented
@magento run all tests

2020-06-05 13:35 UTC, coderimus commented
Failed tests results are not related to the PR changes.

2020-06-05 13:35 UTC, coderimus submitted a review, later dismissed

2020-06-05 17:44 UTC, chalov-anton requested changes
:x: QA Failed

The image disappears from the Media Gallery grid. But if you open Adobe Stock, the **Open in media Gallery** button will be displayed instead of **Save Preview**
![op_in_med_gall](https://user-images.githubusercontent.com/45624059/83906921-18f1e000-a76d-11ea-9598-b79d819cf094.png)
If you'll create a new folder with the same name that has been deleted, an _Uncaught TypeError: Cannot read property 'replace' of undefined_ will appear
![replace](https://user-images.githubusercontent.com/45624059/83907058-62dac600-a76d-11ea-9763-90a9839973b4.png)

2020-06-08 09:09 UTC, gabrieldagama commented
@magento run all tests

2020-06-08 10:08 UTC, sivaschenko requested changes
Hi @gabrieldagama thanks for the pull request, please see my review comment

2020-06-08 10:08 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/masonry.js
> +            $(window).on('enhanced_media_gallery_folder_deleted', this.reloadGrid.bind(this));
Let's rename the event for consistency with other events naming
```suggestion
            $(window).on('folderDeleted.enhancedMediaGallery', this.reloadGrid.bind(this));
```

2020-06-08 10:29 UTC, gabrieldagama commented
@magento run all tests

2020-06-08 10:41 UTC, gabrieldagama commented
@magento run all tests

2020-06-08 14:46 UTC, sivaschenko submitted a review, later dismissed

2020-06-08 14:48 UTC, sivaschenko commented
Static tests need to be fixed

2020-06-08 14:52 UTC, gabrieldagama commented
@magento run Static Tests

2020-06-08 16:24 UTC, gabrieldagama commented
@magento run Static Tests

2020-06-08 19:27 UTC, gabrieldagama commented
@magento run all tests

2020-06-09 08:36 UTC, gabrieldagama commented
@sivaschenko static tests are fixed!

2020-06-09 11:53 UTC, sivaschenko approved these changes

2020-06-09 13:02 UTC, chalov-anton commented
:heavy_check_mark: QA Passed
- the image disappeared from the Media Gallery.
- the **Open in media Gallery** button was changed to **Save Preview**
- also rechecked deleting folder, when there are multiple images.

2020-06-09 13:18 UTC, merged