Verify if current_tree_path folder exists on jstree initialization
magento/adobe-stock-integration pull request #1434
Opened 2020-06-11 09:50 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1406: 400 Post error appears each time when using _wysiwyg_ or changing _catalog/category_ image
2. ...

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Verify that there are no _/wysiwyg_ and _Catalog/category_ Directories
3. Go to **Catalog - Categories**
4. Click **Select from Gallery** button 
_the folder Catalog/category_ Directory appeared and selected in the folder tree_
5.  Observe the dev console 

**No errors in dev console**

2020-06-11 09:52 UTC, Nazar65 commented
@magento run all tests

2020-06-11 10:55 UTC, Nazar65 commented
@magento run all tests

2020-06-12 08:51 UTC, Nazar65 commented
@magento run all tests

2020-06-12 10:47 UTC, gabrieldagama requested changes
Hi @Nazar65, thanks for the pull request! It looks great!

I was thinking, can we avoid the recursive call and rendering the folders twice by doing something like this?

1. Change the `getJsonTree` to return a promise just with the data (it is already doing more than it should).
2. On `initliaze` we can call `createFolderIfNotExists`using the promise from `getJsonTree`, if the folders already exist we can just render the folders using `createTree` otherwise we fetch the getJsonTree again and render it using `createTree`.
3. We will have to change the reloadJsTree to `createTree` on the `getJsonTree` promise.

2020-06-15 09:01 UTC, Nazar65 commented
@magento run all tests

2020-06-15 10:06 UTC, gabrieldagama submitted a review, later dismissed
Hi @Nazar65, thanks for the updates, it looks great!

2020-06-15 10:56 UTC, Nazar65 commented
@magento run all tests

2020-06-15 11:46 UTC, gabrieldagama submitted a review, later dismissed

2020-06-15 12:55 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

The folders are created correctly and there are no errors in dev console

2020-06-15 14:09 UTC, gabrieldagama approved these changes

2020-06-15 15:27 UTC, merged