#1456 - Removed SelectModifierInterface and added CollectionProcessor
magento/adobe-stock-integration pull request #1473
Opened 2020-06-15 14:27 UTC by gabrieldagama

### Description (*)
Removed SelectModifierInterface and added CollectionProcessor to the MediaGalleryUi DataProvider.

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1456: Update media gallery data provider to utilize collection processor and migrate current filters/joins

### Manual testing scenarios (*)
1. Go to `Content` -> `Media Gallery`
2. Test filters, pagination and sorting.

2020-06-15 14:27 UTC, gabrieldagama commented
@magento run all tests

2020-06-15 18:24 UTC, sivaschenko requested changes
Thanks for the PR @gabrieldagama , please see my review comments

2020-06-15 18:24 UTC, sivaschenko commented on AdobeStockImageAdminUi/etc/adminhtml/di.xml
> +    <virtualType name="Magento\MediaGalleryUi\Model\Api\SearchCriteria\CollectionProcessor\JoinProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor\JoinProcessor">
This virtual type is already declared in MediaGalleryUi module, so I think there is no need to specify the type
```suggestion
    <virtualType name="Magento\MediaGalleryUi\Model\Api\SearchCriteria\CollectionProcessor\JoinProcessor">
```

2020-06-15 18:24 UTC, sivaschenko commented on MediaGalleryUi/Model/Listing/DataProvider.php
>              return $this->searchResultToOutput($searchResult);
Unnecessary variable can be eliminated
```suggestion
            return $this->searchResultToOutput($this->getSearchResult());
```

2020-06-15 18:24 UTC, sivaschenko commented on MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Keyword.php
> +                ->joinInner(
let's keep the consistent formatting in this method (let's move `)` to the next line)

2020-06-16 11:04 UTC, gabrieldagama commented
@magento run all tests

2020-06-16 12:28 UTC, sivaschenko approved these changes

2020-06-16 12:29 UTC, sivaschenko commented
@magento run all tests

2020-06-16 15:21 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

Rechecked the:
- filters
- sorting
- pagination

2020-06-17 11:38 UTC, merged