Remove obsolete content after content synchronization 2.0.0-develop
magento/adobe-stock-integration pull request #1483
Opened 2020-06-16 15:11 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1474: The "Used in" still displays that the image is used in a Product after the Product has been deleted
2. ...

### Manual testing scenarios (*)
1. Create a Product and add an image from Media Gallery
2. Go to Content - Media Gallery and View the Details of the image that was previously added to the Product
3. Verify that the Details display that the image is **Used In 1 Product**
4. Go to _Catalog - Products_ and **Delete** the previously created Product
5. Perform ``` bin/magento indexer:reindex, bin/magento media-content:sync, bin/magento cache:clean``` 
6. Go to Go to Content - Media Gallery and View the Details of the image that was previously Used

The image is not Used in a product so it should not be displayed in Details

2020-06-16 15:12 UTC, Nazar65 commented
@magento run all tests

2020-06-16 15:19 UTC, Nazar65 commented
@magento run all tests

2020-06-17 10:00 UTC, Nazar65 commented
@magento run all tests

2020-06-17 16:49 UTC, Nazar65 commented
@magento run all tests

2020-06-17 17:26 UTC, lenaorobei requested changes
Please see minor review commants.

2020-06-17 17:26 UTC, lenaorobei commented on MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php
> +    private const MEDIA_CONTENT_ASSET_TABLE = 'media_content_asset';
```suggestion
```

2020-06-17 17:26 UTC, lenaorobei commented on MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php
> +    private const MEDIA_CONTENT_ASSET_TABLE = 'media_content_asset';
Duplicated in `GetOutdatedRelations`

2020-06-17 17:26 UTC, lenaorobei commented on MediaContentSynchronization/Model/ResourceModel/GetOutdatedRelations.php
> +            $message = __('Could not fetch media content links data');
Would be nice to avoid one-time use variables.

2020-06-17 18:31 UTC, lenaorobei commented
@magento run all tests

2020-06-17 18:31 UTC, lenaorobei submitted a review, later dismissed

2020-06-18 10:43 UTC, chalov-anton requested changes
❌ QA Failed

Counts properly if you delete one entity. But if you delete more than one entity, the counter will remove only one.
For one synchronization, only one entity is removed

For example, 
1) the image is Used in 4 products.
2) user delete 2 products
3) user performs ```media-content:sync```

Actual Result: The View Details will display that the image is Used in 3 products
Expected Result: The View Details displays that the image is Used in 2 products

after another ```media-content:sync``` the View Details will display that the image is Used in 2 products

2020-06-18 12:03 UTC, Nazar65 commented
@magento run all tests

2020-06-18 12:04 UTC, Nazar65 commented
thank you @chalov-anton  could you please verify this issue now ?

2020-06-18 15:00 UTC, chalov-anton commented
✔️ QA Passed

The previous concern is fixed

2020-06-18 17:08 UTC, merged