#1494: Save image content hash to the media asset when saving image from the Adobe Stock
magento/adobe-stock-integration pull request #1508
Opened 2020-06-19 14:35 UTC by joweecaquicla

### Description (*)

This PR will implement the saving of image content hash to the media asset.
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1494: Save image content hash to the media asset when saving image from the Adobe Stock 
2. ...

### Manual testing scenarios (*)

1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Search Adobe Stock" button
4. Click on any image to open the image preview panel
5. Click "Save Preview" button
6. Confirm the image name in the popup

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The hash filed should be populated with the `sha1` hash of the image content

2020-06-19 14:36 UTC, joweecaquicla commented
@magento run all tests

2020-06-22 09:03 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Looks good! Can you please fix the failed unit test

2020-06-22 10:04 UTC, joweecaquicla commented
@magento run all tests

2020-06-29 12:28 UTC, coderimus requested changes
Hi @joweecaquicla ! Thank you for the PR provided 👍 Please, check my change requests below.

2020-06-29 12:28 UTC, coderimus commented on AdobeStockImage/Model/SaveMediaGalleryAsset.php
> +    }
```suggestion
    private function hashImageContent(string $destinationPath): string
    {
        return sha1_file($destinationPath);
    }
```
cc @sivaschenko

2020-06-29 12:28 UTC, coderimus commented on AdobeStockImage/Model/SaveMediaGalleryAsset.php
> +                'hash' => $hashedImageContent
```suggestion
                'hash' => $this->hashImageContent($destinationPath)
```

2020-06-29 12:28 UTC, coderimus commented on AdobeStockImage/Model/SaveMediaGalleryAsset.php
> +            $hashedImageContent = $this->hashImageContent($destinationPath);
We can use the `hashImageContent` directly when assigning value to the array key. Please, remove this line.

2020-07-03 06:42 UTC, coderimus commented on AdobeStockImage/Model/SaveMediaGalleryAsset.php
> +    }
Read the comment https://github.com/magento/adobe-stock-integration/pull/1510#discussion_r444850084 and see the point with the `sha1_file` @joweecaquicla please, ignore my change request.

2020-07-08 14:44 UTC, joweecaquicla commented
@magento run all tests

2020-07-08 16:10 UTC, joweecaquicla commented
@magento run all tests

2020-07-08 17:35 UTC, joweecaquicla commented
@magento run all tests

2020-07-09 12:45 UTC, sivaschenko approved these changes

2020-07-09 12:45 UTC, merged