[WIP] Introduce massaction mod for media gallery
magento/adobe-stock-integration pull request #1509
Opened 2020-06-19 15:39 UTC by Nazar65

### Description (*)

**whats left:** 
1. Delete images in bulk with queue
2. Send request to deleting images
3. Show count of selected images
4. Correct styles to match mockups
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1488: Introduce ability to switch to massaction mode in the media gallery
2. ...

### Manual testing scenarios (*)
1. Open Media Gallery page or slide panel
2. triger manually in console `jQuery(window).trigger('massAction.MediaGallery'); `
 or to terminate massaction mode and switch to default mode `jQuery(window).trigger('terminateMassAction.MediaGallery');`

![Screenshot_2020-06-19 Manage Gallery Media Content Magento Admin](https://user-images.githubusercontent.com/2481206/85151116-0e027980-b25c-11ea-980b-a8ac51a404f8.png)

2020-06-19 15:40 UTC, Nazar65 commented
@magento run all tests

2020-06-19 15:57 UTC, Nazar65 commented
@magento run all tests

2020-06-19 19:12 UTC, Nazar65 commented
@magento run all tests

2020-06-20 08:42 UTC, Nazar65 commented
@magenti run all tests

2020-06-20 08:43 UTC, Nazar65 commented
@magento run all tests

2020-06-20 10:05 UTC, Nazar65 commented
@magento run all tests

2020-06-20 10:10 UTC, Nazar65 commented
@magento run all tests

2020-06-20 10:43 UTC, Nazar65 commented
@magento run all tests

2020-06-20 13:22 UTC, Nazar65 commented
@magento run all tests

2020-06-22 07:56 UTC, Nazar65 commented
@magento run all tests

2020-06-22 09:48 UTC, sivaschenko reviewed
Thanks for the PR @Nazar65 ! Added a couple of comments

2020-06-22 09:48 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
> +                    'You have successfully removed the "%image" ' . $prefix,
Let's have the following success messages:
 - 1 asset: `The asset "%assetName" has been successfully deleted.`
 - more than 1 asset: `The assets have been successfully deleted.`

2020-06-22 09:48 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
> +                'message' => __('Image Ids is required and must be type of array.'),
```suggestion
                'message' => __('Image Ids are required and must be of type array.'),
```

2020-06-22 09:48 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/massactions.js
> +            this.changePageTitle();
I'd extract buttons and title to separate components

2020-06-22 12:21 UTC, Nazar65 commented
@magento run all tests

2020-06-22 12:28 UTC, Nazar65 commented
@magento run all tests

2020-06-22 18:04 UTC, Nazar65 commented
@magento run all tests

2020-06-22 18:09 UTC, Nazar65 commented
@magenot run all tests

2020-06-22 18:39 UTC, Nazar65 commented
@magento run all tests

2020-06-22 18:47 UTC, Nazar65 commented
@magento run all tests

2020-06-22 21:22 UTC, Nazar65 commented
@magento run all tests

2020-06-23 06:33 UTC, Nazar65 commented
@magento run all tests

2020-06-23 08:27 UTC, Nazar65 commented
@magento run all tests

2020-06-23 12:57 UTC, sivaschenko requested changes
Hi @Nazar65 , thanks for the updates! Please see my review comments

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryImageDeleteImagesInBulkActionGroup.xml
> +        <see userInput='The assets have been successfully deleted' stepKey="verifyDeleteImages"/>
Please move the verification to a separate Assert action group

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDeleteImagesInBulkTest.xml
> +         <actionGroup ref="AdminEnhancedMediaGallerySelectIMageForMAssActionActionGroup" stepKey="selectFirstImageToDelete">
```suggestion
         <actionGroup ref="AdminEnhancedMediaGallerySelectImageForMassActionActionGroup" stepKey="selectFirstImageToDelete">
```

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
> +], function ($, _, getDetails, DeleteImages) {
```suggestion
], function ($, _, getDetails, deleteImages) {
```

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/checkboxes.js
> +            this._super().observe(['selectedItems', 'isMassActionMode']);
isMassActionMode doesn't look to be used.

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactions.js
> +            this.selectedItems(this.checkbox().selectedItems());
the selected items are currently duplicated in the massasctions and checkboxes components.

What do you think about having checkbox as part of image component view and reusing the selected property of the image for mass select. In this case we'll need to introduce `isCheckboxVisible` and `isMultipleSelectionEnabled` properties to the image component

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactions.js
> +            if (this.getSelectedCount() >= 1 && !this.massActionMode()) {
I don't think we need this functionality. Checkboxes should be hidden in the regular mode, switching to the massaction mode should only happen on the button click

2020-06-23 12:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactionView.js
> +            document.querySelectorAll(this.gridSelector)[0].addEventListener('DOMSubtreeModified', function () {
I think it might be better to handle that by introducing `isContextMenuVisible` property to the image component and using knockout js bindings

2020-06-24 09:33 UTC, Nazar65 commented
@magento run all tests

2020-06-25 11:02 UTC, sivaschenko submitted a review, later dismissed

2020-06-26 14:59 UTC, chalov-anton requested changes
:x: QA Failed

When you activate the massaction mode by clicking **Delete Selection...**, DON'T select any images and click **Delete image** - a confirmation message appears _Are you sure you want to delete "0" images?_
![delete0](https://user-images.githubusercontent.com/45624059/85870918-5da1f180-b7d6-11ea-815a-80ced552c4de.png)

After confirming, an _Image Ids are required and must be of type array._ error and a 400 Bage request appears
![image_ids array](https://user-images.githubusercontent.com/45624059/85871100-9cd04280-b7d6-11ea-9bff-05159ca2ae01.png)
![Peek 2020-06-26 17-59](https://user-images.githubusercontent.com/45624059/85871247-cdb07780-b7d6-11ea-82d0-27ce429ed8ef.gif)

2020-06-26 15:26 UTC, Nazar65 commented
@magento run all tests

2020-06-26 15:27 UTC, Nazar65 commented
thanks for the QA @chalov-anton could you please verify again ? i've added a pop up alert in this case
![Screenshot_2020-06-26 Manage Gallery Media Content Magento Admin(1)](https://user-images.githubusercontent.com/2481206/85874084-bffcf100-b7da-11ea-92ac-500e92e81a36.png)

2020-06-26 17:10 UTC, lenaorobei commented
@magento run all tests

2020-06-26 18:21 UTC, chalov-anton requested changes
When an image is selected, two similar **Delete Selected** buttons are displayed
![2delete selected](https://user-images.githubusercontent.com/45624059/85888645-aa93c100-b7f2-11ea-9ea7-1867d0c6eb3b.png)

Please rename the **Delete Selected…** into **Delete Images…**
https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/4b2e4f6d-8b87-4c51-8161-be77b5add80a/Media-Gallery

2020-06-30 11:40 UTC, Nazar65 commented
@magento run all tests

2020-06-30 15:50 UTC, Nazar65 commented
@magento run all tests

2020-06-30 17:21 UTC, Nazar65 commented
@magento run all tests

2020-06-30 17:25 UTC, Nazar65 commented
@magento run all tests

2020-07-01 06:35 UTC, Nazar65 commented
Hi @chalov-anton  i'v implemented the last issue on the "massaction mode story" could you please check the functionality now ?

2020-07-01 09:36 UTC, sivaschenko approved these changes

2020-07-01 12:14 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

Great job :+1:  
The test on the Cucumber https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/3962787 (the test state is _In Progress_)

2020-07-02 12:12 UTC, merged