Update license action visibilite based on overlay as is_lecensed column not exist anymore
magento/adobe-stock-integration pull request #1519
Opened 2020-06-23 12:34 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1517: "License" button is available for already Licensed and locally Uploaded images 
2. ...

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. **Sign in** Adobe Stock
3. Save a Licensed image
4. Select the previously saved licensed image from Media Gallery
5. Click on "three dots" and verify is the **License** button is available

The License button should not be available for already licensed images

2020-06-23 12:36 UTC, Nazar65 commented
@magento run all tests

2020-06-23 13:00 UTC, sivaschenko requested changes
Thanks for the fix @Nazar65 ! Can you please cover the case with the MFTF test and switch the base branch to `2.0.0-develop`

2020-06-23 14:23 UTC, Nazar65 commented
@magento run all tests

2020-06-23 14:53 UTC, Nazar65 commented
@magento run all tests

2020-06-23 16:12 UTC, Nazar65 commented
@magento run all tests

2020-06-24 12:27 UTC, sivaschenko approved these changes

2020-06-24 12:28 UTC, merged