Introduce asset filter for Category grid
magento/adobe-stock-integration pull request #1587
Opened 2020-07-09 13:14 UTC by Nazar65

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1502: add asset filter to category grid
2. ...

### Manual testing scenarios (*)
1.Open Category grid page by link `admin/media_gallery_catalog/category/index`
2. Expand Filters tab
3. Put asset path in Asset filter input
![Screenshot_2020-07-09 Categories Magento Admin](https://user-images.githubusercontent.com/2481206/87044432-292f2c00-c1ff-11ea-9f50-bc623422b38e.png)

2020-07-09 13:14 UTC, Nazar65 commented
@magento run all tests

2020-07-09 13:47 UTC, Nazar65 commented
@magento run all tests

2020-07-09 20:18 UTC, Nazar65 commented
@magento run all tests

2020-07-10 08:10 UTC, Nazar65 commented
@magento run all tests

2020-07-10 13:49 UTC, Nazar65 commented
@magento run all tests

2020-07-10 14:49 UTC, Nazar65 commented
@magento run all tests

2020-07-13 09:47 UTC, Nazar65 commented
@magento run all tests

2020-07-13 10:56 UTC, Nazar65 commented
@magento run all tests

2020-07-13 11:19 UTC, Nazar65 commented
@magento run all tests

2020-07-13 11:59 UTC, sivaschenko requested changes
Thanks for the PR @Nazar65 ! Please see my review comments

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/form/element/ui-select.js
> +        getPath: function (data) {
Can we avoid the need to extend the component by using showPath=false configuration and just using a custom template

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/ui_component/product_listing.xml
> +                        <item name="searchUrl" xsi:type="url" path="media_gallery/image/getassetsoptions" />
Let's use the following naming for consistency
```suggestion
                        <item name="searchUrl" xsi:type="url" path="media_gallery/asset/search" />
```

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/ui_component/product_listing.xml
> +                name="asset"
```suggestion
                name="asset_id"
```

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/ui_component/product_listing.xml
> +                        <item name="chipsEnabled" xsi:type="boolean">true</item>
Please add 

                        <item name="filterPlaceholder" xsi:type="string" translate="true">Asset Title</item>
                        <item name="emptyOptionsHtml" xsi:type="string" translate="true">Start typing to find assets</item>

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertCategoryNameInCategoryGridActionGroup.xml
> +
unnecessary empty line

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Image/GetAssetsOptions.php
> +namespace Magento\MediaGalleryUi\Controller\Adminhtml\Image;
```suggestion
namespace Magento\MediaGalleryUi\Controller\Adminhtml\Asset;
```

2020-07-13 11:59 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Image/GetAssetsOptions.php
> +class GetAssetsOptions extends Action implements HttpGetActionInterface
```suggestion
class Search extends Action implements HttpGetActionInterface
```

2020-07-13 12:35 UTC, Nazar65 commented
@magento run all tests

2020-07-13 12:37 UTC, gabrieldagama requested changes
Hi @Nazar65, thanks for the PR, it looks great! Please follow some small comments.

2020-07-13 12:37 UTC, gabrieldagama commented on MediaGalleryUi/Ui/Component/Listing/Filters/Asset.php
> +    private const CTAEGORY_ENTITY_TYPE = 'catalog_category';
We can probably remove this constant.

```suggestion
```

2020-07-13 12:37 UTC, gabrieldagama commented on MediaGalleryUi/Ui/Component/Listing/Filters/Asset.php
> +    private function getCategoryIdsByAsset(array $ids): string
I guess this wasn't meant to be only for categories right? We might want to rename this one.
```suggestion
    private function getEntityIdsByAsset(array $ids): string
```

2020-07-13 12:46 UTC, Nazar65 commented
@magento run all tests

2020-07-13 19:58 UTC, Nazar65 commented
@magento run all tests

2020-07-14 08:26 UTC, Nazar65 commented
@magento run all tests

2020-07-14 08:44 UTC, Nazar65 commented
@magento run all tests

2020-07-14 09:05 UTC, Nazar65 commented
@magento run all tests

2020-07-14 14:12 UTC, Nazar65 commented
@magento run all tests

2020-07-14 15:03 UTC, Nazar65 commented
@magento run all tests

2020-07-16 20:19 UTC, Nazar65 commented
@magento run all tests

2020-07-17 06:56 UTC, sivaschenko approved these changes

2020-07-17 11:15 UTC, chalov-anton commented
:heavy_check_mark: Great job

The **Asset** filter works on: _Product_, _Page_, _Category_, and _Blocks_ pages.
Added a scenario to Regression Scope - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951024

2020-07-20 09:59 UTC, merged

2020-07-20 09:59 UTC, ghost commented
Hi @Nazar65, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+adobe-stock-integration+1587), it will take less than a minute. </br>Your feedback will help us to improve contribution process.