Added Content Status and Store View filters
magento/adobe-stock-integration pull request #1602
Opened 2020-07-16 10:55 UTC by gabrieldagama

### Description (*)
Added Content Status and Store View filters.

1. Depends on https://github.com/magento/magento2/pull/29058

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1463 
2. Fixes magento/adobe-stock-integration#1464

### Manual testing scenarios (*)

1. Assign an asset to a content (product, category, page or block)
2. Go to `Content` -> `Media Gallery` and filter by `Content Status` or `Store View`
3. The filter output should be assets that are used on content and the content matches the filter condition.

2020-07-16 10:59 UTC, gabrieldagama commented
@magento run all tests

2020-07-16 11:24 UTC, gabrieldagama commented
@magento run all tests

2020-07-16 12:36 UTC, gabrieldagama commented
@magento run all tests

2020-07-16 13:36 UTC, gabrieldagama commented
@magento run all tests

2020-07-17 10:11 UTC, gabrieldagama commented
@magento run all tests

2020-07-17 13:41 UTC, chalov-anton commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDisabledContentFilterTest.xml
> +            <testCaseId value="to-be-added"/>
```suggestion
            <testCaseId value="https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4970565"/>
```

2020-07-17 13:41 UTC, sivaschenko requested changes
Thanks for the PR @gabrieldagama , please see my comments

2020-07-17 13:41 UTC, sivaschenko commented on MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/ContentField.php
> +    private const TABLE_ALIAS = 'main_table';
A bit of inconsistency: there is a constant for the table name but no constant for `id` field name. I'd have both on none

2020-07-17 13:41 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryApplySelectFilterActionGroup.xml
> +            <argument name="selectOption" type="string"/>
`filterLabel` and `optionLabel` argument names would be more descriptive for a developer

2020-07-17 13:41 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
> +        <element name="selectFilterInput" type="button" selector="//label[@class='admin__form-field-label']/span[text()='{{filterLabel}}']/parent::*/parent::div/div[@class='admin__form-field-control'
Why do these selectors have `Input` in  the name?

2020-07-17 13:41 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/ActionGroup/AdminOpenMediaGalleryForExistingPageNoEditorActionGroup.xml
> +    <actionGroup name="AdminOpenMediaGalleryForExistingPageNoEditorActionGroup">
Can you please replace existing usages of `AdminOpenMediaGalleryForPageNoEditorActionGroup` with opening a page and using this action group.

Also I'd correct a name as I believe this action group should work not only for the existing page
```suggestion
    <actionGroup name="AdminOpenMediaGalleryFromPageNoEditorActionGroup">
```

2020-07-17 13:41 UTC, sivaschenko commented on MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryStoreViewContentFilterTest.xml
> +    <test name="AdminMediaGalleryStoreViewContentFilterTest">
I'd also add a store view filter test for the category to cover the specific implementation

2020-07-17 13:41 UTC, sivaschenko commented on modman
> +@import MediaGalleryContentUi
Please remove the obsolete import

2020-07-17 17:49 UTC, gabrieldagama commented
@magento run all tests

2020-07-21 08:58 UTC, sivaschenko submitted a review, later dismissed

2020-07-21 08:59 UTC, sivaschenko commented
@magento run all tests

2020-07-21 09:00 UTC, sivaschenko submitted a review, later dismissed

2020-07-21 11:24 UTC, gabrieldagama commented
@magento run all tests

2020-07-21 12:56 UTC, gabrieldagama commented
@magento run all tests

2020-07-21 13:29 UTC, chalov-anton commented
:heavy_check_mark: Great job

The _Store view_ filter handles multiple Sites and Views perfectly 
![store_view](https://user-images.githubusercontent.com/45624059/88060583-1d345a00-cb6f-11ea-8617-d5a7b2c35009.png)

The _Content status_ filter works for Enabled and Disabled Pages, Blocks, Products, Categories

The filters work together with other already existing filters

2020-07-21 16:38 UTC, merged