[WIP] #1444: Save metadata to file on editing
magento/adobe-stock-integration pull request #1607
Opened 2020-07-19 13:43 UTC by yolouiese

### Need to verify (*)
- No errors will be encountered and data will be saved successfully after transferring save logic from controller to a model
- Title and description metadata are saved to file

### Description (*)
- Transferred save logic from controller to model and added implementation for saving metadata to file

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1444: Save metadata to file on editing

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery and click the "three dots" from the bottom right
3. Select **Edit**
4. Update either the title or description fields
5. Click save

2020-07-19 13:43 UTC, yolouiese commented
@magento run all tests

2020-07-19 16:40 UTC, yolouiese commented
@magento run all tests

2020-07-19 17:36 UTC, yolouiese commented
@magento run all tests

2020-07-20 05:51 UTC, yolouiese commented
@magento run all tests

2020-07-21 12:26 UTC, sivaschenko requested changes
Thanks for the pull request @yolouiese ! Please see my comments

2020-07-21 12:26 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Image/SaveDetails.php
>              $asset = current($this->getAssetsByIds->execute([$imageId]));
I think it would be better to pass the `$imageId` to the SaveImageDetails model and retrieve the asset there

2020-07-21 12:26 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +    public function updateMetadata(
Public access is not necessary
```suggestion
    private function updateMetadata(
```

2020-07-21 12:26 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +        $mediaDirectory = $this->fileSystem->getDirectoryWrite(DirectoryList::MEDIA);
Write access is not necessary
```suggestion
        $mediaDirectory = $this->fileSystem->getDirectoryRead(DirectoryList::MEDIA);
```

2020-07-21 12:26 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +        } catch (CouldNotSaveException $e) {
CouldNotSaveException is already localized, catching and throwing it again is not necessary

2020-07-21 12:26 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +            'keywords' => $imageKeywords
`AssetKeywordsInterface` expects keywords of type `KeywordInterface[]`

2020-07-22 10:29 UTC, yolouiese commented
@magento run all tests

2020-07-22 10:51 UTC, sivaschenko requested changes
Thanks for updates @yolouiese ! Please see my comments

2020-07-22 10:51 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +    public function execute($imageId, $imageKeywords, $imageTitle, $imageDescription): void
```suggestion
    public function execute(int $imageId, array $imageKeywords, string $imageTitle, string $imageDescription): void
```

2020-07-22 10:51 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +     * @param null|string $imageId
all these params cannot be null

2020-07-22 10:51 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +    private function updateMetadata(
please specify parameter types and remove the `null` from annotation

2020-07-22 10:51 UTC, sivaschenko commented on MediaGalleryUi/Model/SaveImageDetails.php
> +use Psr\Log\LoggerInterface;
There are too many dependencies, let's also extract keywords and metadata processing to 2 separate modules to make each class simplier

2020-07-22 19:50 UTC, yolouiese commented
@magento run all tests

2020-07-23 11:58 UTC, sivaschenko submitted a review, later dismissed

2020-07-23 11:58 UTC, sivaschenko commented
@magento run all tests

2020-07-23 14:07 UTC, sivaschenko commented
@magento run all tests

2020-07-23 14:18 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

Successfully updated the image _Title_ and _Description_

2020-07-26 13:45 UTC, sivaschenko commented
@magento run all tests

2020-07-26 14:45 UTC, sivaschenko commented
@magneto run all tests

2020-07-26 19:17 UTC, sivaschenko commented
@magneto run all tests

2020-07-26 19:56 UTC, sivaschenko commented
@magento run all tests

2020-07-27 08:22 UTC, merged