#1620: Not possible to enter multi-line image Description
magento/adobe-stock-integration pull request #1624
Opened 2020-07-21 13:26 UTC by joweecaquicla

### Description (*)

This PR will fix the issue wherein it is not possible to enter multi-line image description by clicking Enter.
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integrationhttps://github.com/magento/adobe-stock-integration/issues/1620: Not possible to enter multi-line image Description 
2. ...

### Manual testing scenarios (*)

1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit**
4. Place the cursor to the **Description** field
5. Type any text, and hit Enter key
6. The cursor should go to the next line.

2020-07-21 13:27 UTC, joweecaquicla commented
@magento run all tests

2020-07-21 13:34 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Can you please check if the fix from https://github.com/magento/adobe-stock-integration/pull/1597/files can be applied in a different way to avoid reintroducing the issue

2020-07-21 14:03 UTC, sivaschenko approved these changes

2020-07-22 10:03 UTC, chalov-anton commented
Hello @joweecaquicla 

Great job on the enter key behavior. The cursor is moved to the next line on _Description_ field and **Saves** image on _Title_ field.
Tab key, switches from _Title_ field to _Description_ field 
![Peek 2020-07-22 12-55](https://user-images.githubusercontent.com/45624059/88163406-49a5b000-cc1b-11ea-98e0-c86013e686f2.gif)


:x: The only thing is that, for some reason, a multiline Description. doesn't pass the validation
![Selection_044](https://user-images.githubusercontent.com/45624059/88163564-84a7e380-cc1b-11ea-87a1-368d5d56cf6f.png)

Do you think you can fix this in the scope of this PR? 
Thank you

2020-07-22 10:21 UTC, joweecaquicla commented
Hi @chalov-anton!
This PR contains the fix for that issue and it is not yet merged: https://github.com/magento/adobe-stock-integration/pull/1608/files

2020-07-22 10:32 UTC, chalov-anton commented
Thank you, I'm moving this PR to _Ready for Delivery_

2020-07-22 10:45 UTC, merged