#1609: [Refactoring] DateTime handling and formatting
magento/adobe-stock-integration pull request #1625
Opened 2020-07-21 13:50 UTC by yolouiese

### Need to verify (*)
- **Created** and **Modified** values are saved and displayed without any issues when viewing image details

### Description (*)
- Refactored datetime handling and formatting by adding/using Magento Framework DateTime functionality 

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1609: [Refactoring] DateTime handling and formatting

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Search for any image from the **Search Adobe Stock** button
2. Select the added image from Media Gallery and click "three dots" in the bottom right
3. Select **View Details**
4. Check **Created** and **Modified** values under **Details**

2020-07-21 13:50 UTC, yolouiese commented
@magento run all tests

2020-07-21 14:16 UTC, sivaschenko requested changes
Thanks for the pull request @yolouiese ! Please take a look at my comment

2020-07-21 14:16 UTC, sivaschenko commented on MediaGalleryUi/Model/AssetDetailsProvider/CreatedAt.php
> +        DateTime $date
I think it's better to use `\Magento\Framework\Stdlib\DateTime\TimezoneInterface` for retrieving and formatting a date (only for view layer, not applicable to `SynchronizeFiles` class)

2020-07-22 11:32 UTC, yolouiese commented
@magento run all tests

2020-07-23 12:03 UTC, sivaschenko submitted a review, later dismissed

2020-07-24 09:14 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

_Created_ and _Modified_ dates are displayed under Image Details
The _Modified_ date and time is updated after Editing

2020-07-26 14:06 UTC, sivaschenko commented
@magento run all tests

2020-07-27 08:22 UTC, merged