#1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed
magento/adobe-stock-integration pull request #1715
Opened 2020-08-04 11:27 UTC by jmonteros422

### Description (*)

This PR fixes issue related to #1688

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed

### Manual testing scenarios (*)

1. Go to **Catalog - Categories**, 
2. Expand **Content**, click **Select from Gallery**
3. Click **Search Adobe Stock**
4. Save an Image Preview
5. Observe if the Image is selected/highlighted and if **Add Selected** button appeared

### Expected result (*)
The Image is selected/highlighted and **Add Selected** button appeared
![selected_er](https://user-images.githubusercontent.com/45624059/89038332-d30a6000-d348-11ea-9907-23a43abf9e77.png)

2020-08-04 11:28 UTC, jmonteros422 commented
@magento run all tests

2020-08-06 07:36 UTC, sivaschenko requested changes
Thanks for the pull request @jmonteros422 ! Please see my comments

2020-08-06 07:36 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
> +                .toggleAddSelectedButton();
I think it migth be better to use the `select` method that is responsible for handling that action
```suggestion
            uiRegistry.get('name =' + this.mediaGallery).select(record);
```

2020-08-06 07:36 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
> +                .toggleAddSelectedButton();
Also can you please add `mediaGallery` property to defaults

2020-08-06 10:16 UTC, jmonteros422 commented
@magento run all tests

2020-08-07 13:31 UTC, sivaschenko requested changes
Thanks for updates @jmonteros422 ! The implementation look good! Can you please ensure this case is covered by an MFTF test (save preview image from adobe stock and add it to the content straight away)
@chalov-anton can you please provide the cucumber test case for MFTF test

2020-08-10 10:53 UTC, jmonteros422 commented
@magento run all tests

2020-08-10 12:09 UTC, sivaschenko requested changes
Thanks for updates @jmonteros422 ! Please see my comment

2020-08-10 12:09 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminMediaGalleryAddSelectedSavedPreviewActionGroup.xml
> +    <actionGroup name="AdminMediaGalleryAddSelectedSavedPreviewActionGroup">
Please use `AdminSaveAdobeStockImagePreviewActionGroup` and `AdminMediaGalleryClickAddSelectedActionGroup` instead of this action group

2020-08-10 13:02 UTC, jmonteros422 commented
@magento run all tests

2020-08-10 20:04 UTC, sivaschenko approved these changes

2020-08-10 20:07 UTC, sivaschenko commented
@magento run all tests

2020-08-11 07:39 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed
The Image is selected/highlighted and Add Selected button appeared
![Screenshot_72](https://user-images.githubusercontent.com/60198022/89870608-c7c3f980-dbbe-11ea-94b8-5652fd1973c3.png)

Manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/5068945)

2020-08-11 10:22 UTC, merged