Integration test coverage for rendition image generation
magento/adobe-stock-integration pull request #1762
Opened 2020-08-18 01:22 UTC by konarshankar07

### Description (*)

This PR will cover the integration test for Rendition image generation services 
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1751: [2.1-develop] Cover renditions services with integration tests

2020-08-18 01:23 UTC, konarshankar07 commented
@magento run all tests

2020-08-18 04:41 UTC, konarshankar07 commented
@magento run all tests

2020-08-18 10:43 UTC, sivaschenko requested changes
Thanks for the PR @konarshankar07 ! Please see my comments

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
> +    public function testExecute(): void
Please use a dataProvider for testing of different images
```suggestion
    public function testExecute(string $path, string $expectedRenditionPath): void
```

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
> +    public static function tearDownAfterClass(): void
I think only `.renditions` the directory should be removed in this method.

Considering that it's better to use data provider to retrieve image path - the test can use the path from dataprovider to copy the image to the media gallery and to remove the image after the test

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
> +        copy($fixtureDir . self::LARGE_SIZE_IMAGE, self::$mediaDir . self::LARGE_SIZE_IMAGE);
I'd copy the file directly in the test. That way the only source of image path is going to be dataprovider and the constants can be removed.

Also please use the `\Magento\Framework\Filesystem\DriverInterface` for copying files. 

```
        $absolutePath = realpath(__DIR__ . '/../../_files/' . $path);
        $mediaAbsolutePath = $this->mediaDirectory->getAbsolutePath($path);
        $this->driver->copy(
            $absolutePath,
            $mediaAbsolutePath
        );
```

Also, I think it's better to move the test images one directory up to the `Test` directory as they can be potentially reused by other types of tests

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
> +    protected static $mediaDir;
Please avoid using static properties, it would be safer to ensure the test has a clear state each time it is run

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +        $this->generateRenditions->execute([self::LARGE_SIZE_IMAGE, self::MEDIUM_SIZE_IMAGE]);
Please use dataProvider to make it easier to add more cases later

2020-08-18 10:43 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +    public static function setUpBeforeClass(): void
See my comments for the next tests

2020-08-26 18:31 UTC, konarshankar07 commented
@magento run all tests

2020-08-27 05:39 UTC, konarshankar07 commented
@magento run all tests

2020-08-27 12:32 UTC, konarshankar07 commented
@magento run all tests

2020-08-27 13:02 UTC, sivaschenko requested changes
Thanks for updates @konarshankar07 ! Please see my comments

2020-08-27 13:02 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +        if ($isRenditionsGenerated) {
Condition can be simplified:
```suggestion
        if (!$isRenditionsGenerated) {
            $this->assertFileDoesNotExist($expectedRenditionPath);
            return;
        }
```

2020-08-27 13:02 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +        $expectedRenditionPath = $this->mediaDirectory->getAbsolutePath($renditionPath);
I think it does not make sence to have `$paths` as array if the test is working with only one `$renditionPath`.

Please revert `$paths` to string

2020-08-27 13:02 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
> +        $this->assertEquals($expectedRenditionPath, $getRenditionPath);
Unnecessary variable
```suggestion
        $this->assertEquals($expectedRenditionPath, $this->getRenditionPath->execute($path));
```

2020-08-27 13:02 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +                'Generated renditions image width should be less than or equal to original image'
```suggestion
                'Generated renditions image width should be less than or equal to configured value'
```

2020-08-27 13:02 UTC, sivaschenko commented on MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
> +                'Generated renditions image height should be less than or equal to original image'
```suggestion
                'Generated renditions image height should be less than or equal to configured value'
```

2020-08-27 17:33 UTC, konarshankar07 commented
@magento run all tests

2020-08-27 17:35 UTC, sivaschenko approved these changes

2020-08-28 05:13 UTC, konarshankar07 commented
@magento run Integration Tests

2020-08-28 10:49 UTC, merged