[WIP] #1787: Cover GetAssetListInterface with an integration test
magento/adobe-stock-integration pull request #1803
Opened 2020-09-02 21:12 UTC by yolouiese

### Description (*)
This PR covers the integration test for GetAssetListInterface class

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1787: Cover GetAssetListInterface with an integration test

2020-09-03 10:39 UTC, sivaschenko commented
Changed base branch to 2.1-develop, please use the default repo branch for pull requests

2020-09-07 08:21 UTC, yolouiese commented
@magento run all tests

2020-09-07 13:09 UTC, yolouiese commented
@magento run all tests

2020-09-07 17:31 UTC, sivaschenko requested changes
Thanks for PR @yolouiese ! Please see my comment

2020-09-07 17:31 UTC, sivaschenko commented on AdobeStockAsset/Test/Integration/Model/GetAssetListTest.php
> +                ConnectionWrapper::class => ConnectionWrapperMock::class
I'd replace the `Magento\AdobeStockClientApi\Api\ClientInterface` with a mock. That approach would avoid the dependency of AdobeStockAsset module on the library and client implementation. Also, I believe `ClientInterface` should be easier to mock.

2020-09-08 13:27 UTC, yolouiese commented
@magento run all tests

2020-09-09 09:07 UTC, sivaschenko requested changes
Thanks for updates @yolouiese ! Please see my comments

2020-09-09 09:07 UTC, sivaschenko commented on AdobeStockAsset/Test/Integration/Model/ClientMock.php
> +        } catch (IntegrationException $exception) {
It's better to output/forward any occuring exceptions instead of catching and logging them for integration tests

2020-09-09 09:07 UTC, sivaschenko commented on AdobeStockAsset/Test/Integration/Model/ClientMock.php
> +                $items[] = $this->stockFileToDocument->convert($file);
There is no need to first generate `SearchFilesResponse` with `StockFile`sand then convert it to the document. Let's create documents straight away and avoid the dependency to Adobe Stock SDK (`\AdobeStock` namespace classes should not be used for this test)

2020-09-09 09:07 UTC, sivaschenko commented on AdobeStockAsset/Test/Integration/Model/ClientMock.php
> +    private function getNextResponse(): SearchFilesResponse
I guess that's an only response we can get
```suggestion
    private function getResponse(): SearchFilesResponse
```

2020-09-09 20:00 UTC, yolouiese commented
@magento run all tests

2020-09-10 12:55 UTC, sivaschenko approved these changes

2020-09-11 15:24 UTC, sivaschenko commented
@magento run Integration Tests

2020-09-12 18:22 UTC, merged