#1801: User is not scrolled up to the "Login failed. Please check if the Secret Key..." error, and can miss the message
magento/adobe-stock-integration pull request #1818
Opened 2020-09-08 10:24 UTC by yolouiese

### Description (*)
Added a modification to scroll to the top of the modal to show the error message after unsuccessful licensing from Media Gallery

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1801: User is not scrolled up to the "Login failed. Please check if the Secret Key..." error, and can miss the message

### Manual testing scenarios (*)
**Preconditions**
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Old Media Gallery enabled in Stores -> Configuration -> Advanced-> System -> Media Gallery -> Enable Old Media Gallery - No
4. Provided _API Key (Client ID)_ . **Not** provided _Client Secret_
5. Multiple images saved to Media Gallery, (four rows of images in my case)
6. Unlicensed image preview saved to Media Gallery being at the bottom of images

**Testing Steps**
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Scroll to the bottom of the page
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **License**

2020-09-08 10:25 UTC, yolouiese commented
@magento run all tests

2020-09-08 12:18 UTC, sivaschenko requested changes
Hi @yolouiese , thanks for the PR! Please see my comment

2020-09-08 12:18 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
> +                $(errorMessageSelector).get(0).scrollIntoView({
Depending on how `licenseProcess` method will be used the error may or may not be shown to the user, also the selector of error message depends on the view layer implementation. Please move this action to the place where the error is actually added to the content.

2020-09-09 09:00 UTC, yolouiese commented
Closing this PR in favor of https://github.com/magento/magento2/pull/29947.

2020-09-09 09:00 UTC, closed without merging