[WIP] #1802: The "three dots" context menu is not closed after unsuccessful licensing from Media Gallery
magento/adobe-stock-integration pull request #1826
Opened 2020-09-10 22:07 UTC by joweecaquicla

### Description (*)

This PR will introduce the MFTF test for the fix on https://github.com/magento/adobe-stock-integration/issues/1802. Link of the fix's PR: https://github.com/magento/magento2/pull/29967
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration https://github.com/magento/adobe-stock-integration/issues/1802: The "three dots" context menu is not closed after unsuccessful licensing from Media Gallery
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

2020-09-10 22:08 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-11 09:52 UTC, sivaschenko requested changes
Thanks for the test @joweecaquicla ! Please see my comments

2020-09-11 09:52 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageActionsSection.xml
> +        <element name="contextMenu" type="block" selector="//div[@class='media-gallery-image']//ul[@class='action-menu _active']//li//a[@class='action-menu-item']"/>
I'd rename this element to the `contextMenuItem` and move it to MediaGalleryUi (as this is the module introducing this menu)

2020-09-11 09:52 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryUnsuccessfulLicensingTest.xml
> +        <dontSeeElement selector="{{AdminEnhancedMediaGalleryImageActionsSection.contextMenu}}" stepKey="verifyContextMenuIsClosed" />
Let's extract this check to AssetAdminMediaGalleryContextMenuOpenedGroup (and place it in the MediaGalleryUi module)

2020-09-11 09:52 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryUnsuccessfulLicensingTest.xml
> +            <actionGroup ref="AdminAdobeStockSetConfigActionGroup" stepKey="setIncorrectAdobeSecret">
Please revert the configuration changes in `after` section

2020-09-11 09:52 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryUnsuccessfulLicensingTest.xml
> +            <actionGroup ref="AdminSearchImagesOnModalActionGroup" stepKey="searchForUnlicensedImage">
Please reset the filters applied to adobe stock grid in `after` section

2020-09-11 09:52 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryUnsuccessfulLicensingTest.xml
> +        <actionGroup ref="AdminAdobeStockImsPopupSignInFillUserDataActionGroup" stepKey="fillUserCredentials"/>
This test might need to be skipped by default with a link to an issue https://github.com/magento/adobe-stock-integration/issues/1170

2020-09-12 18:29 UTC, merged