#1786 :- Replace DocumentToAssetTest unit test with an integration test
magento/adobe-stock-integration pull request #1831
Opened 2020-09-14 06:03 UTC by konarshankar07

### Description (*)

This PR will replace the Unit test to Integration test for `Replace \Magento\AdobeStockImage\Test\Unit\Model\Extract\DocumentToAssetTest`
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1786: Replace DocumentToAssetTest unit test with an integration test

2020-09-14 06:03 UTC, konarshankar07 commented
@magento run all tests

2020-09-14 10:11 UTC, sivaschenko requested changes
Thanks for the pull request @konarshankar07 ! Please see my review comments

2020-09-14 10:11 UTC, sivaschenko commented on AdobeStockImage/Test/Integration/Model/Extract/DocumentToAssetTest.php
> +        $this->assertEquals($creatorData, $documentToAsset->getCreator()->getData());
`\Magento\AdobeStockAssetApi\Api\Data\CreatorInterface` and other data interfaces does not have the `getData` method declared.

Can you please replace `getData` calls to `\Magento\Framework\Reflection\DataObjectProcessor::buildOutputDataArray`

2020-09-14 10:11 UTC, sivaschenko commented on AdobeStockImage/Test/Integration/Model/Extract/DocumentToAssetTest.php
> +        $this->documentToAsset = Bootstrap::getObjectManager()->get(
The `documentToAsset` instance is created for each test run in `setUp` method, no need to create it in the test

2020-09-14 10:11 UTC, sivaschenko commented on AdobeStockImage/Test/Integration/Model/Extract/DocumentToAssetTest.php
> +        $documentToAsset = $this->documentToAsset->convert($document, $additionalData);
Naming clarification suggestion
```suggestion
        $asset = $this->documentToAsset->convert($document, $additionalData);
```

2020-09-14 10:11 UTC, sivaschenko commented on AdobeStockImage/Test/Integration/Model/Extract/DocumentToAssetTest.php
> +            ]
I'd create the document instance in  the test, not to duplicate the data. I believe it's enough to have only two  parameters in the test
```suggestion
            'case1' => [
                'data' => [
                        'id' => 1,
                        'category' => [
                            'id' => 2,
                            'name' => 'The Category'
                        ],
                        'creator_name' => 'Creator',
                        'creator_id' => 3,
                        'is_licensed' => 1
                    ],
                'additionaData' => [
                    'media_gallery_id' => 5
                ]
            ]
```

2020-09-15 05:21 UTC, konarshankar07 commented
@magento run all tests

2020-09-15 08:16 UTC, konarshankar07 commented
@magento run all tests

2020-09-15 12:23 UTC, sivaschenko approved these changes

2020-09-15 12:24 UTC, merged