User controls access to Adobe Stock images from Admin Panel in ACL
magento/adobe-stock-integration pull request #263
Opened 2019-07-29 11:27 UTC by engcom-Golf

### Description (*)
Implemented MFTF test to cover scenario: "User controls access to Adobe Stock images from Admin Panel in ACL"

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#198: Issue title

### Manual testing scenarios (*)
Run functional tests

2019-08-27 01:12 UTC, diazwatson commented
@Nazar65 I get this exception when running this test, could you please take a look?

```
ASI-198$ bin/mftf run:test UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest

DEPRECATION: Test StorefrontOnePageCheckoutJsValidationTest is missing required annotations.{"testName":"StorefrontOnePageCheckoutJsValidationTest","missingAnnotations":"stories"}

In ActionMergeUtil.php line 286:

  Section cannot use names more than once.
  	name: firstImageAfterSearch is used more than once. (Parent: AdobeStockSection)
  	in file: /adobestock/ext/magento/stock-integration/AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml.
  Exception occurred parsing action at StepKey "disableWYSYWYG"
```

2019-08-27 14:29 UTC, engcom-Golf commented
Hi @diazwatson ok

2019-08-27 15:06 UTC, sivaschenko requested changes
Thanks for the PR @engcom-Golf ! Can you please update the branch, adjust the test to the updates and add verification of requirements from the story https://github.com/magento/adobe-stock-integration/issues/42 : effect of corresponding resources turned on/off for a role.

2019-08-27 15:06 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest.xml
> +            <amOnPage url="admin/admin/auth/logout/" stepKey="amOnLogoutPage"/>
please use logout action group

2019-08-27 15:06 UTC, sivaschenko commented on AdobeStockImageAdminUi/Test/Mftf/Test/UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest.xml
> +        <grabAttributeFrom selector="{{AdobeStockSection.firstImageAfterSearch}}" userInput="src"
Please use verification approach from `AdminUserAccessesAdobeStockPanelTest`

2019-08-28 09:14 UTC, engcom-Golf commented on AdobeStockImageAdminUi/Test/Mftf/Test/UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest.xml
> +            <amOnPage url="admin/admin/auth/logout/" stepKey="amOnLogoutPage"/>
ok

2019-08-28 09:14 UTC, engcom-Golf commented on AdobeStockImageAdminUi/Test/Mftf/Test/UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest.xml
> +        <grabAttributeFrom selector="{{AdobeStockSection.firstImageAfterSearch}}" userInput="src"
ok

2019-08-28 09:18 UTC, engcom-Golf commented
Hi @sivaschenko thank you for review, i'm updated PR  due to new review comment, can you please review new changes ?

2019-08-28 19:59 UTC, sivaschenko approved these changes

2019-08-28 20:00 UTC, merged