277: save asset keywords + provide keywords repository
magento/adobe-stock-integration pull request #304
Opened 2019-08-06 17:42 UTC by coderimus

### Description
This PR is a provided solution for issue [277: Save keywords asset data along with the asset.](https://github.com/magento/adobe-stock-integration/issues/277)

This implementation has 2 main parts:
* save keywords along with the asset object by using latest Magneto 2 approach: use resource services for data storage manipulation to avoid as much inheritance as possible. Also, save keywords action provided as a multiply items save process. As an example, the Inventory module was taken as a guide.
* Keyword repository functionality added because of possible keywords management at the Magento side or service requests or webapi requests. It also implemented with some new features: use resource services (command classes) to proxy repository requests. Here, as I can see, it is not possible at this moment to completely avoid using Abstract DB classes in the inheritance because it does 2 main things, from my point of view: manage load process and before/after save events.

**QUESTIONS**
Is it a required state for a keyword object to implement extension attributes? For the getList and get asset actions?

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
Save asset and check keywords data.

2019-08-08 15:57 UTC, coderimus commented
@sivaschenko about unit tests: will make a separate issue for this after the architect and implementation approve. The tests are have to be complex for this part of the project and do not want to spend a lot of resources on them before approve what to test :)

2019-08-09 21:37 UTC, sivaschenko requested changes
Hi @coderimus thanks for your pull request, please see my review comments

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAssetApi/Api/KeywordRepositoryInterface.php
> +    public function save(\Magento\AdobeStockAssetApi\Api\Data\KeywordInterface $keyword): int;
```suggestion
    public function save(\Magento\AdobeStockAssetApi\Api\Data\KeywordInterface $keyword): void;
```

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAssetApi/Api/Data/KeywordInterface.php
> +    const ASSET_KEYWORD_KEYWORD_ID = 'keyword_id';
I don't think the last two constants make sense in the keyword scope

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAsset/Model/ResourceModel/Keyword/SaveMultiplyAndAssignToAsset.php
> +            $assignedKeywords = $this->getAlreadyAssignedKeywords($asset);
I don't think there is any need to know which keywords are already assigned and which are not during the save operation.

The save keyword operation may be as simple as:
`insert ignore into adobe_stock_keyword (keyword) values ('apple');`
`insert ignore into adobe_stock_asset_keyword (keyword_id, asset_id) values (24, 42);`

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAsset/Model/ResourceModel/Keyword/SaveMultiplyAndAssignToAsset.php
> +            $keywordIds = $this->selectKeywordsIdsByNames($keywords);
I don't think there is any need to know keyword ids during save/assign operation

The save keyword operation may be as simple as:
`insert ignore into adobe_stock_keyword (keyword) values ('apple');`
`insert ignore into adobe_stock_asset_keyword (keyword_id, asset_id) values (24, 42);`

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAsset/Model/AssetRepository.php
> +        $this->saveMultiplyAndAssignToAsset->execute($asset);
As there is a keyword repository - it should be responsible for saving keywords, all extra entry points to save keyword action should be removed to have a single entry point.

```suggestion
        $this->keywordRepository->save($assetId, $asset->getKeywords());
```

2019-08-09 21:37 UTC, sivaschenko commented on AdobeStockAsset/Model/KeywordRepository.php
> +class KeywordRepository implements KeywordRepositoryInterface
There should be a single entry point to operations with keywords. Either a repository or separate services but not both. I'd go with repository not to overengineer the trivial keyword operations

2019-08-11 19:35 UTC, sivaschenko approved these changes

2019-08-11 19:38 UTC, sivaschenko commented
@coderimus the repository was removed from the pull request as there are concerns about the implementation (the keyword implementation was partially based on standard resource model and partially on the custom resource model) approach and it is not needed currently. Let's discuss the changes and approach to the repository.

Anyway, this pull request is a great job! I appreciate your thoughtful and wide implementations!

2019-08-11 19:38 UTC, merged