Move masonry grid to AdobeUi module
magento/adobe-stock-integration pull request #334
Opened 2019-08-09 13:23 UTC by engcom-Golf

### Description (*)
Move masonry grid to AdobeUi module (prepare for moving to magento2)

Moved the masonry grid to AdobeUI module:

- Images grid
- Image preview (only next, previous and close controls)

### Fixed Issues (if relevant)
1. magento/adobe-stock-integration#314: Move masonry grid to AdobeUi module (prepare for moving to magento2)

### Manual testing scenarios (*)
1. Configure Adobe stock
2. Search images.

2019-08-13 03:35 UTC, sivaschenko requested changes
Thanks for the pull request @engcom-Golf @Nazar65 ! Please review my comments

2019-08-13 03:35 UTC, sivaschenko commented on AdobeUi/README.md
> +# Magento_AdobeStockImage Module
Please update readme

2019-08-13 03:35 UTC, sivaschenko commented on AdobeUi/Ui/Component/Listing/Columns/ImagePreview.php
> +namespace Magento\AdobeUi\Ui\Component\Listing\Columns;
Only image preview with navigation (next/forward/close) should be moved to AdobeUi. Displaying image attributes and buttons should still be part of AdobeStockImageAdminUi functionality (extending AdobeUi)

2019-08-13 03:35 UTC, sivaschenko commented on AdobeUi/composer.json
> +    "name": "magento/module-ui",
```suggestion
    "name": "magento/module-adobe-ui",
```

2019-08-13 03:35 UTC, sivaschenko commented on AdobeUi/composer.json
> +        "magento/module-adobe-stock-asset-api": "*",
AdobeUi module is an extraction of masonry grid and overlay that will be delivered to Magento core. It should not depend on other adobestock modules

2019-08-13 08:46 UTC, engcom-Golf commented
Hi @sivaschenko I'm updated code by your review notes.

2019-08-13 10:48 UTC, engcom-Golf commented on AdobeUi/README.md
> +# Magento_AdobeStockImage Module
ok

2019-08-18 21:33 UTC, sivaschenko approved these changes

2019-08-18 21:35 UTC, sivaschenko approved these changes

2019-08-18 21:36 UTC, merged