#298 : Introduce GetAssetList API service
magento/adobe-stock-integration pull request #335
Opened 2019-08-09 18:01 UTC by konarshankar07

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#298: Introduce GetAssetList API service.

2019-08-09 18:01 UTC, konarshankar07 commented
Once changes are approved then I'll start working on Unit testing and webapi testing
Thanks

2019-08-12 03:54 UTC, sivaschenko requested changes
Thanks for the pull request, there is one small change request. Let's wait for https://github.com/magento/adobe-stock-integration/pull/303 to be merged before moving the unit test

2019-08-12 03:54 UTC, sivaschenko commented on AdobeStockImage/Model/GetImageList.php
> +    private $assetList;
As this is a command (not a collection) let's name it accordingly to avoid confusion
```suggestion
    private $getAssetList;
```

2019-08-13 23:01 UTC, diazwatson requested changes
@konarshankar07 please look at the unit test
```
vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-stock-image/Test/Unit
```
```
1) Magento\AdobeStockImage\Test\Unit\Model\GetImageListTest::testExecute
Mock_AssetSearchResultsInterface_08f5fe61 Object &000000000bb64aa3000000001d5e6adc (
    '__phpunit_invocationMocker' => null
    '__phpunit_originalObject' => null
    '__phpunit_configurable' => Array &0 (
        0 => 'getitems'
        1 => 'setitems'
        2 => 'getsearchcriteria'
        3 => 'setsearchcriteria'
        4 => 'gettotalcount'
        5 => 'settotalcount'
    )
) is not instance of expected class "Mock_AssetSearchResultsInterface_9a8d8999".
--- Expected
+++ Actual
@@ @@
-Mock_AssetSearchResultsInterface_9a8d8999 Object &000000000bb64ab0000000001d5e6adc (
+Mock_AssetSearchResultsInterface_08f5fe61 Object &000000000bb64aa3000000001d5e6adc (
/home/travis/build/magento/adobe-stock-integration/ext/magento/adobe-stock-integration/AdobeStockImage/Test/Unit/Model/GetImageListTest.php:111
```

2019-08-14 05:23 UTC, konarshankar07 commented
Hello @diazwatson 
Please check @sivaschenko  [comment](https://github.com/magento/adobe-stock-integration/pull/335#pullrequestreview-273503393). But I still can start working on API testing
Thanks

2019-08-19 19:16 UTC, sivaschenko approved these changes

2019-08-19 19:41 UTC, diazwatson approved these changes

2019-08-19 19:41 UTC, merged