330: Remove unused fields from DB schema
magento/adobe-stock-integration pull request #354
Opened 2019-08-13 15:14 UTC by coderimus

### Description (*)
According to the issue description, the next fields were deleted from the database schemas and also related metadata interface methods.
1. stock_id
1. vector_type
1. preview_width
1. prview_height
1. country_name
1. thumbnail_url
1. preview_url
1. details_url
1. preminum_level_id
1. url

**IMPLEMENTATION DETAILS**

**whitelist JSON update**
The whitelist JSON for the asset table schema also updated with the native Magento command.

**get/set for thumbnail and preview URLs**
The thing which can initiate a discussion is the get/set thumbnail URL and preview URL. They are needed to be included in the Asset object because we send it to the UI component. If the Asset object doesn't have them as set/get methods, the search result factory logic will exclude them from the response. In that case, we have two variants:

* leave those methods at the metadata class interface - AssetInterface and implement them
* use extension attributes functionality to add them to the Asset object.

I decided to provide them as a part of the metadata object because they are required components of the Asset object for UI.

***Change  AssetInterface::ADOBE_IDconstant to the  AssetInterface::ID**
The  `AssetInterface::ADOBE_ID` doesn't exist. Changed it to  `AssetInterface::ID` for tests.

### Fixed Issues (if relevant)
#330 Remove unused fields from DB schema

### Manual testing scenarios (*)
Upgrade the DB structure and try to save the asset.

2019-08-13 17:06 UTC, sivaschenko requested changes
@coderimus Thanks for the pull request! I think we should keep the methods in the AssetInterface as it's used to get data from the API.

2019-08-20 16:39 UTC, sivaschenko requested changes
Thanks for the update, please update database schema for the constraint names to match the whitelist

2019-08-20 17:19 UTC, coderimus commented
@sivaschenko thank you for your review. Requested changes implemented. Please, check. Also, I deleted unused constants and renamed the creator_name column name to the name for the creator table.

2019-08-20 18:00 UTC, sivaschenko approved these changes

2019-08-20 18:02 UTC, merged