373: image related image series - base implementation
magento/adobe-stock-integration pull request #385
Opened 2019-08-25 13:16 UTC by coderimus

### Description (*)
This PR is the first initial implementation for the image series functionality. PR provides the back-end part along with the basic frontend implementation: ajax async call with data managing.

#### How it works?
The preview image block has a new element - <div> "More from this series". On its render on preview image activate the getImageSeries function executes and requested for the image related series. On success call of this request, the image list is returned and rendered.

The Image series is the list of assets filtered by the image id. To get it a new filter introduced - the Series. 
It handles the `serie_id` parameter. Serie id is the image adobe id.

#### Questions
1. Should we store the image series returned value per image in the observable array and return it on the second image preview attempt? Or request the image series every image preview section visit?
1. What value should we use as the default image preview item limit to render? 

#### Notes
* I decided to add the image series serialize simple class to separate the get image series data and its preparation for a response.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

2019-08-25 19:27 UTC, sivaschenko requested changes
Hi @coderimus thanks for the pull request! Great work! The only thing I can suggest - is reducing the amount of code by reusing `SimpleFilters` class DI configuration and reducing the number of conversions by working with `DocumentInterface` instead of `AssetInterface`. Please see my review comments!

2019-08-25 19:27 UTC, sivaschenko commented on AdobeStockClient/Model/SearchParametersProvider/Series.php
> +class Series implements SearchParameterProviderInterface
Looks like there is no required custom logic in this parameter provider. Can series be included as part of simple filters?

2019-08-25 19:27 UTC, sivaschenko commented on AdobeStockImage/Model/GetImageSeries.php
> +            foreach ($items as $item) {
Is it necessary to convert series items to asset interface? If not, it's ok to operate `DocumetInterface`s. I don't think there is any chance they will be saved to the database.

2019-08-25 19:27 UTC, sivaschenko commented on AdobeStockImage/Model/ImageSeriesSerialize.php
> +    public function execute(array $series): array
I'd propose to use the existing hydrator to extract data from `DocumentInterface`

2019-08-26 10:03 UTC, coderimus commented
@sivaschenko thank you for your review and suggested improvements. I think I got the point: the image series is just a simple data which is needed only to rendered at the specific place. And it doesn't have any other role in the system. According to this, I made the next changes:

1. represent the series filter as a simple filter
1. allow the SimpleFilters set int type variables (previously, escaper transform the int into the string when calling the set filter value method)
1.  move image series serialise logic to the GetImageSeries model and make it works with Document instead of Asset

Please, review the latest comment to this branch.

2019-08-27 14:40 UTC, sivaschenko approved these changes

2019-08-27 14:40 UTC, merged