fix When clicked too fast on SearchAdobeStock error: container undefined
magento/adobe-stock-integration pull request #417
Opened 2019-09-04 13:13 UTC by engcom-Golf

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#414: When clicked too fast on Search Adobe Stock error: this.container undefined
2. ...

### Manual testing scenarios (*)
1. Configure Adobe stock
2. Go to Catalog-> category-> content tab ->insert image-> Adobe Stock Search
3. Grid rendered correctly no errors in console.

**Before**
![deepin-screen-recorder_Select area_20190904160438](https://user-images.githubusercontent.com/51681547/64257648-60251900-cf2e-11e9-9ad0-d0b9bf0ec094.gif)

**After**
![deepin-screen-recorder_Select area_20190904160338](https://user-images.githubusercontent.com/51681547/64257685-6ca97180-cf2e-11e9-91f5-65314d1f147c.gif)

2019-09-25 18:44 UTC, sivaschenko commented
Hi @engcom-Golf @Nazar65 thanks for the pull request. What do you think about adjusting the fix to wait for `this.container` being initialized in the `setLayoutStyles` function of `masonry.js` component?

2019-09-26 06:42 UTC, Nazar65 commented
Hi @sivaschenko  yes , i will try.

2019-10-01 13:38 UTC, engcom-Golf commented
HI @sivaschenko done :heavy_check_mark:  now all works perfectly

2019-10-05 17:17 UTC, sivaschenko requested changes

2019-10-05 17:17 UTC, sivaschenko commented on AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
> +            if (this.imports.rows.length === 0 || typeof this.container === "undefined") {
```suggestion
            if (this.rows.length === 0 || typeof this.container === "undefined") {
```
Imports defaults configuratioin is actually setting the `rows` property

2019-10-05 17:51 UTC, sivaschenko approved these changes

2019-10-05 17:51 UTC, merged