Move default premium filter to di.xml configuration
magento/adobe-stock-integration pull request #492
Opened 2019-09-27 07:37 UTC by Nazar65

### Description (*)
By default premium filter is set to All in \Magento\AdobeStockClient\Model\SearchParametersProvider\Premium::apply

Instead of setting the default filter in Client, it now sets by adding the filter to Magento\AdobeStockImage\Model\GetImageList in AdobeStockImage/etc/di.xml

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#471: Move default premium filter to di.xml configuration
2. ...

### Manual testing scenarios (*)
1. Configure Adobe Stock integration
2. Open Adobe Stock search
3. Verify premium filter all applied
4. Chose in grid filters filter premium
5. Verify filter applied.

2019-09-27 12:00 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! Please see my code review comments

2019-09-27 12:00 UTC, sivaschenko commented on AdobeStockImage/etc/di.xml
> +                    <item name="field" xsi:type="string">all</item>
I think it's worth to try to use `Magento\AdobeStockClient\Model\SearchParametersProvider\SimpleFilters` for Premium filter. It should be possible after accepting the following suggestion:
```suggestion
                    <item name="field" xsi:type="string">ALL</item>
```

2019-09-27 12:51 UTC, Nazar65 commented
@sivaschenko done :heavy_check_mark:

2019-10-01 09:46 UTC, sivaschenko approved these changes

2019-10-01 16:49 UTC, merged