#486 : [Styles] "See more" related images link is shifted out of image preview area on tablet
magento/adobe-stock-integration pull request #495
Opened 2019-09-27 09:29 UTC by konarshankar07

### Description (*)

This PR fixed some styling issue which is caused due to https://github.com/magento/adobe-stock-integration/pull/481 and also fixed the see more styling issue in tablet

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#486: [Styles] "See more" related images link is shifted out of image preview area on tablet

### Manual testing scenarios (*)

1.Use tablet or adjust the browser to iPad resolution (768X1024)
2. Login to admin panel
3. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
4. Click "Search Adobe Stock" button to open images grid
5. Click on any image to expand image preview
6. Expected Result 
![image](https://user-images.githubusercontent.com/39480008/65758681-1e574f00-e137-11e9-9d89-73bfdedf2eb6.png)

2019-09-29 22:04 UTC, diazwatson commented
@konarshankar07 thanks for your contribution.
Could you please have a look at the git conflicts with:

```
AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
```

2019-09-29 22:05 UTC, diazwatson requested changes
@konarshankar07 thanks for your contribution

Could you please have a look at the conflicts with 

```
AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
```

2019-09-30 14:28 UTC, diazwatson submitted a review, later dismissed

2019-10-01 10:09 UTC, sivaschenko approved these changes

2019-10-01 10:09 UTC, merged

2019-10-01 10:09 UTC, ghost commented
Hi @konarshankar07, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+adobe-stock-integration+495), it will take less than a minute. </br>Your feedback will help us to improve contribution process.