Set modules and dependency versions
magento/adobe-stock-integration pull request #648
Opened 2019-11-04 23:07 UTC by sivaschenko

Set modules and dependency versions

2019-11-05 15:51 UTC, YevSent requested changes

2019-11-05 15:51 UTC, YevSent commented on AdobeStockAdminUi/composer.json
> +        "magento/module-adobe-ims-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockAdminUi/composer.json
> +        "magento/module-adobe-stock-client-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockAsset/composer.json
> +        "magento/module-adobe-stock-client-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockAsset/composer.json
> +        "magento/module-adobe-media-gallery-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

Also, I suppose this package should be moved to the core.

2019-11-05 15:51 UTC, YevSent commented on AdobeStockAsset/composer.json
> +        "magento/module-adobe-media-gallery": "100.0.*",
Why this package has dependencies on both API and non-API packages?

2019-11-05 15:51 UTC, YevSent commented on AdobeStockClient/composer.json
> +        "magento/module-adobe-ims-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockImage/composer.json
> +        "magento/module-adobe-stock-asset-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockImage/composer.json
> +        "magento/module-adobe-media-gallery-api": "100.0.*"
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:51 UTC, YevSent commented on AdobeStockImageAdminUi/composer.json
> +        "magento/module-adobe-stock-client-api": "100.0.*",
PHP Interface (marked with @api) | Inject in a constructor and/or call methods | MAJOR
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#determine-module-dependency

2019-11-05 15:59 UTC, YevSent commented on AdobeIms/composer.json
> +    "version": "100.0.0"
As those packages are not core modules, I would suggest using `1.0.0` as a version.

2019-11-05 17:07 UTC, sivaschenko commented on AdobeStockAsset/composer.json
> +        "magento/module-adobe-media-gallery-api": "100.0.*",
AdobeMediaGallery and AdobeUi modules will be removed from this repo after they will be merged to core

2019-11-05 17:10 UTC, sivaschenko commented on AdobeStockAsset/composer.json
> +        "magento/module-adobe-media-gallery": "100.0.*",
Non-API package is installing a database table that is referenced in AdobeStockAsset db table foreign key

2019-11-06 18:28 UTC, sivaschenko commented on AdobeIms/composer.json
> +    "version": "100.0.0"
Changed

2019-11-06 18:35 UTC, sivaschenko commented
@joni-jones versions are updated according to review comments. Please review

2019-11-06 21:43 UTC, YevSent approved these changes

2019-11-06 23:50 UTC, merged