#768 : [1.1-develop] Introduce MediaGalleryUi module
magento/adobe-stock-integration pull request #773
Opened 2019-11-24 15:11 UTC by konarshankar07

### Description (*)

This PR will introduce MediaGalleryUi module which will be responsible for Media gallery user interface
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#<issue_number>: [1.1-develop] Introduce MediaGalleryUi module

### Manual testing scenarios (*)

1. Login into Magento Backend
2. Check the configuration in in Stores -> Configuration -> Advanced -> System -> Media Gallery fieldset

### Screenshot

![image](https://user-images.githubusercontent.com/39480008/69496692-b9cc2c80-0efa-11ea-977c-4bda56b8421b.png)

2019-11-24 15:14 UTC, konarshankar07 commented
Hello @sivaschenko ,
Do we also need to implement the data service contract for `config.php` in `MediaGalleryUiApi` module?

2019-11-24 17:22 UTC, sivaschenko requested changes
Hi @konarshankar07 thanks for the pull request! Congratulations on creating a first PR to 1.1 version!

Please take a look at my review comments.

As for `ConfigInterface` in `MediaGalleryUiApi`- I moved that work to a separate task https://github.com/magento/adobe-stock-integration/issues/774

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/Test/Unit/Model/ConfigTest.php
> +        $this->config->isEnabled();
This test does not actually test the result of `isEnabled` method call. I'd use a data provider to check both `true` and `false` values and add an assertion:
```suggestion
        $this->assertEquals(true, $this->config->isEnabled());
```

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/Model/Config.php
> +    private const XML_PATH_ENABLED = 'media/gallery/enabled';
Please update the path to (also affects the unit test, config.xml and system.xml):
```suggestion
    private const XML_PATH_ENABLED = 'media_gallery/general/enabled';
```

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/Model/Config.php
> +     * Is media gallery enabled
```suggestion
     * Check if masonry grid UI is enabled for Magento media gallery
```

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/Model/Config.php
> + * Class Config
```suggestion
 * Class responsible to provide access to system configuration related to the Media Gallery
```

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/composer.json
> +        "magento/module-cms": "*"
I think we can suggest installing "magento/module-media-gallery", but not "magento/module-cms".

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/composer.json
> +        "magento/module-ui": "*"
There is no dependency on backend and ui modules currently

2019-11-24 17:22 UTC, sivaschenko commented on MediaGalleryUi/modman
> +./ app/code/Magento/MediaGalleryUi
Global modman file should be updated as well

2019-11-24 17:27 UTC, sivaschenko commented on MediaGalleryUi/etc/adminhtml/system.xml
> +                    <label>Enabled Media Gallery</label>
No need to specify "Media Gallery" both in fieldset and field names
```suggestion
                    <label>Enabled</label>
```

2019-11-25 20:09 UTC, sivaschenko approved these changes

2019-11-25 20:09 UTC, merged