[WIP] UNIT TEST COVERAGE: cover the service command with unit tests
magento/adobe-stock-integration pull request #812
Opened 2019-11-29 11:57 UTC by coderimus

### Description (*)
Cover with Unit Tests the files command

### Fixed Issues (if relevant)
#811 

### Manual testing scenarios (*)
N/A

2019-12-02 22:48 UTC, sivaschenko requested changes
Hi @coderimus thanks for the pull request! Please see my review comments

2019-12-02 22:48 UTC, sivaschenko commented on AdobeStockClient/Model/Client/Files.php
> +use Magento\Framework\Webapi\Exception as WebApiException;
ok..

2019-12-02 22:48 UTC, sivaschenko commented on AdobeStockClient/Test/Unit/Model/Client/Files/CurlRequestFailed.php
> +            ->willReturn(null);
No need to declare returning `null` explicitly

2019-12-02 22:48 UTC, sivaschenko commented on AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultSuccessFilesExistsTest.php
> +            ->method('setHeaders')
I believe `->with(...)` on `setHeaders` method is one of the most important assertions in the test

2019-12-02 22:48 UTC, sivaschenko commented on AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultContainsEmptyFilesTest.php
> +            ->willReturn('string');
It's better to keep return values close to their actual possible value - as it helps to read the tests/test results

2019-12-02 22:48 UTC, sivaschenko commented on AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultContainsEmptyFilesTest.php
> +            ->willReturn('string');
Values used in unit tests should be assigned to variables. There are 2 possible situations:
1. Value is used verification of value flow - should be stored in a variable and used at least 2 times
2. Value is used as an argument to a method call - it is a good idea to provide such values from data provider as they can be used for boundary testing

2019-12-03 15:33 UTC, coderimus commented
@sivaschenko thank you for your detail review. Requested and suggested changes done. Please, check when you will have time.

2019-12-09 13:24 UTC, sivaschenko approved these changes

2019-12-09 13:24 UTC, merged