#834 : Add upload date filter to media gallery grid
magento/adobe-stock-integration pull request #842
Opened 2019-12-04 14:58 UTC by konarshankar07

### Description (*)

This PR will add the upload date filter in media gallery grid
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#834: Add upload date filter to media gallery grid

### Manual testing scenarios (*)

1. Log in to Admin Panel
2. Select "Media Gallery Development" from the menu on the right
3. Expand filters section
### Expected Result
![image](https://user-images.githubusercontent.com/39480008/70153230-9f513a80-16d4-11ea-910d-f96aca99bd4b.png)

2019-12-06 14:07 UTC, sivaschenko commented
Hi @konarshankar07 thanks for the Pull request! Does this filter require any updates on backend side?

2019-12-06 17:28 UTC, konarshankar07 commented
Hello @sivaschenko ,
Yes, we still need to implement the logic for the applied filter but as per ticket description I thought that I need to add the filter component in this PR and logic implementation in another PR. But I'll now work on filter implementation logic
Thanks

2019-12-09 15:35 UTC, sivaschenko commented
@konarshankar07 the problem is that there is no way to test the filter unless it's implemented in the backend. So I think it should be added in this PR. Let me know if you need any help.

Same thing about https://github.com/magento/adobe-stock-integration/pull/843

2019-12-11 07:43 UTC, chalov-anton commented
Please, add an ability to select Date Range.  Regarding the first item from the **Acceptance Criteria** of the Story https://github.com/magento/adobe-stock-integration/issues/756 , user should be able to _select a date range_  
Like, for example in the Filter from _Customers- All Customers_ 
![dofb](https://user-images.githubusercontent.com/45624059/70601284-621c0980-1bfa-11ea-8f32-676f8b44b4d8.png)

2019-12-11 14:02 UTC, konarshankar07 commented
@chalov-anton
I have realized my mistake after reading AC of the mention story and will update the field in my next commit
Thanks

2019-12-12 15:12 UTC, sivaschenko commented
Hi @konarshankar07 let put the development of pull request on hold until https://github.com/magento/adobe-stock-integration/pull/843 is merged

2019-12-18 21:54 UTC, sivaschenko commented
Hi @konarshankar07 please follow these instructions to add value/filter to the media gallery grid https://github.com/magento/adobe-stock-integration/wiki/Adding-values-filters-to-media-gallery-grid

Upload date is reflected as `created_at` field of Media Gallery asset

2019-12-24 16:14 UTC, sivaschenko requested changes

2019-12-24 16:14 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/css/source/_module.less
> +& when (@media-common = true) {
I don't think any special styles for media gallery are required

2019-12-24 16:15 UTC, sivaschenko approved these changes

2019-12-24 16:16 UTC, merged