#827 : Element '#adobe-stock-tabs-content .three-dots' can be overlapped by "Similar keywords"
magento/adobe-stock-integration pull request #853
Opened 2019-12-06 18:34 UTC by konarshankar07

### Description (*)

This PR will fix the overlap issue with see more element in related image section for kindle device
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#827: Element '#adobe-stock-tabs-content .three-dots' can be overlapped by "Similar keywords"

### Manual testing scenarios (*)

1. On CMS edit page try to add an image by searching
2. In Chrome Dev Tools toggle Device Toolbar and choose Kindle Fire HDX in landscape mode

### Expected Result
![image](https://user-images.githubusercontent.com/39480008/70346745-03b2fc00-1885-11ea-9109-26a50ca0087f.png)

2019-12-09 20:35 UTC, sivaschenko commented
Thanks for the pull request @konarshankar07 ! The PR fixes the issue on iPad, but related images look a bit squashed (not occupying the dedicated space) on bigger screens:

![image](https://user-images.githubusercontent.com/2028541/70469953-f20a6800-1ac1-11ea-96b0-5fe311e398b3.png)

I think either relative units or media query should be applied

2019-12-09 20:36 UTC, sivaschenko requested changes
Thanks for the pull request @konarshankar07 ! The PR fixes the issue on iPad, but related images look a bit squashed (not occupying the dedicated space) on bigger screens:

![image](https://user-images.githubusercontent.com/2028541/70469953-f20a6800-1ac1-11ea-96b0-5fe311e398b3.png)

I think either relative units or media query should be applied

2019-12-11 15:08 UTC, sivaschenko approved these changes

2019-12-12 08:36 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-12-12 13:50 UTC, merged