[WIP] Display folders filter as a directory tree
magento/adobe-stock-integration pull request #936
Opened 2020-01-24 15:44 UTC by Nazar65

Added jquery.jstrre, and service wich deliver directory listing for
jstree plugin

### Description (*)

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#831: Display folders filter as a directory tree
2. ...

### Preconditions
1. Install Magento with Adobe Stock Integration

### Steps to reproduce (*)
1. Login to Admin Panel
2. Select "Media Gallery Development" from the menu on the right
3. Expand filters section

### Actual result (*)

Directory filter is a regular select html element:

![DeepinScreenshot_select-area_20200124174427](https://user-images.githubusercontent.com/2481206/73081873-0dde9780-3ed1-11ea-9e78-9bf525f5e9e5.png)

**TODO:** 
1. Add styles to match mockup
2. Resolve "children" directories to be displayed correctly
3. Setup filter on "click" event

2020-02-10 00:34 UTC, diazwatson submitted a review, later dismissed

2020-02-11 16:39 UTC, diazwatson commented
Forgot to add my screen:
<img width="1415" alt="Screenshot 2020-02-06 at 16 37 28" src="https://user-images.githubusercontent.com/1080386/74257629-04d13100-4ced-11ea-810a-1b3cb8fbf8ba.png">

2020-02-11 17:12 UTC, Nazar65 commented
@diazwatson wow, looks like srltyles os missing, will recheck

2020-02-12 09:29 UTC, diazwatson commented
Thanks @Nazar65 let me know when you ready for me to re test

2020-02-12 13:56 UTC, Nazar65 commented
@diazwatson well after you switched to this branch you need to re deploy static content, and all related styles should be added
![DeepinScreenshot_select-area_20200212155712](https://user-images.githubusercontent.com/2481206/74341299-2515f400-4db0-11ea-8781-0414cdeff9d4.png)

2020-02-12 14:57 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! Please see my review comments

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/templates/directory_container.phtml
> +<script>
I think its better to use jquery widget as proxy to UI components like we do with panels and grids: i.e. `MediaGalleryUi/view/adminhtml/web/js/container.js`

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +            $directoryInstance = $this->filesystem->getDirectoryRead($this->path);
Please extract the logic to a model

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
> +    </columns>
Please remove extra spaces

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
> +            getDirectoryTreeUrl: 'media_gallery/directories/gettree',
The image component is used to render image column, it should not be aware of directories tree

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
> +    private $url;
This column should not be aware of directory tree. A dedicated `class` can be assigned to the directory tree container in the xml to prepare the URL

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/css/source/_module.less
> +            background-image: none !important;
please avoid `!important` in the css

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/css/source/_module.less
> +            background-image: url("../../images/d.png") !important;
```suggestion
            background-image: url("@{baseDir}Magento_MediaGalleryUi/images/d.png");
```

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +    private $responseContent;
This property is not necessary, a local variable should be used instead

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +    private function buildFolderTree(array $directories, bool $skipRoot = true): array
Is it possible to perform the final folder tree creation in the directory iterator loop? (for better performance)

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +    private function findParent(array &$node, array &$treeNode, int $level = 0): array
I believe the custom implementation of recursive directory iteration would help to reduce the algorithm complexity (no need to search for parent if the algorithm builds tree configuration level by level).

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> +                treeInitData: []
Why do we need `options` parent node? Is there any other options that we might use?

2020-02-12 14:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> +                async: false,
I think this ajax call can be done asynchronously if `createTree` is called in the success callback

2020-02-13 07:46 UTC, Nazar65 commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +            $directoryInstance = $this->filesystem->getDirectoryRead($this->path);
ok

2020-02-13 07:46 UTC, Nazar65 commented on MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
> +    </columns>
ok

2020-02-17 12:13 UTC, merged