[WIP] : #906 Add sorting for the Media Gallery
magento/adobe-stock-integration pull request #938
Opened 2020-01-25 05:35 UTC by konarshankar07

### Description (*)

This PR will introduce sorting functionality in media gallery grid
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#906: Add sorting for the Media Gallery

### Manual testing scenarios (*)

1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)

### Expected Result
![image](https://user-images.githubusercontent.com/39480008/73116780-745fc600-3f62-11ea-9fb7-1b7f845ce846.png)

2020-01-25 05:36 UTC, konarshankar07 commented
Hello @sivaschenko ,
If you approve the above changes then I'll work on tests
Thanks

2020-01-27 12:27 UTC, sivaschenko requested changes
Thanks for the pull request @konarshankar07!

The media gallery module should not depend on Adobe Stock Integration (as that is an extension).

I think it would be best to move sorting component and template to Magento_Ui module.
It's better to copy the toolbar template to Magento_MediaGalleryUi module as there is high chance this template is going to be unique per grid

2020-01-27 12:27 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
> +    <listingToolbar name="listing_top" template="Magento_AdobeStockImageAdminUi/grid/toolbar">
media gallery should not depend on Magento_AdobeStockImageAdminUi, we have to either copy the template or move it to Magento_Ui module to use in both modules.

2020-01-27 12:27 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/sorting.js
> +            template: 'Magento_AdobeStockImageAdminUi/sorting',
media gallery should not depend on Magento_AdobeStockImageAdminUi, we have to either copy the template or move it to Magento_Ui module to use in both modules.

2020-01-27 12:27 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/sorting.js
> +            var columns = uiRegistry.get('index = media_gallery_columns');
It would be good to extract this selector to options

2020-01-27 12:27 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/sorting.js
> +                direction: 'desc'
It would be good to extract this selector to options

2020-01-27 18:22 UTC, konarshankar07 commented
Thanks for the feedback and I'll create new PR in the magento 2 repo to move the `sorting` component in `Magento_Ui` module

2020-02-13 12:21 UTC, sivaschenko commented
@konarshankar07 `_masonry-grid.less`, thanks

2020-04-01 18:30 UTC, slavvka commented
@magento run all tests

2020-04-02 04:22 UTC, konarshankar07 commented
Hello @chalov-anton ....
I have added **Sorting by Uploaded date** as per your request in https://github.com/magento/magento2/pull/26736#issuecomment-607295868 PR
Thanks

2020-04-02 07:23 UTC, chalov-anton commented
> Hello @chalov-anton ....
> I have added **Sorting by Uploaded date** as per your request in [magento/magento2#26736 (comment)](https://github.com/magento/magento2/pull/26736#issuecomment-607295868) PR
> Thanks

Thanks a lot!

2020-04-04 14:54 UTC, sivaschenko approved these changes

2020-04-04 14:54 UTC, merged