Added license status filter to Media Gallery
magento/adobe-stock-integration pull request #943
Opened 2020-02-02 10:01 UTC by drpayyne

### Description 

Added a License Status filter to the Media Gallery

### Fixed Issues
magento/adobe-stock-integration#901: Add license status filter

### Manual testing scenarios
1. Have licensed and unlicensed Adobe Stock images in your instance
1. Open Media Gallery -> Filters
2. Verify 'License Status' filter works as expected

2020-02-02 10:24 UTC, Nazar65 requested changes
Hi @drpayyne thanks for the pull request.

> The filter should be added by extending the media_gallery_listing ui listing from AdobeStockImage

This functionality must present only if AdobeStockModule present, so media gallery should not know about licensed functionality

2020-02-02 10:24 UTC, Nazar65 commented on MediaGalleryUi/Ui/Options/Licensed.php
> +
Please add the copyright

2020-02-03 12:37 UTC, Nazar65 commented
Hi @drpayyne  could you please revert the file permission ?
![DeepinScreenshot_select-area_20200203143750](https://user-images.githubusercontent.com/2481206/73653760-af64a680-4692-11ea-9a45-83503340f810.png)

2020-02-03 12:50 UTC, drpayyne commented
Hi @Nazar65, thank you for reviewing! I was in the process of testing it and hadn't pushed my changes. I've pushed my update now. Please review, thanks!

2020-02-03 12:50 UTC, Nazar65 requested changes

2020-02-03 12:50 UTC, Nazar65 commented on AdobeStockImage/Ui/Options/Licensed.php
> +     * {@inheritdoc}
```suggestion
     * @inheritdoc
```

2020-02-03 13:16 UTC, Nazar65 submitted a review, later dismissed

2020-02-04 18:54 UTC, sivaschenko approved these changes

2020-02-04 18:54 UTC, merged