Added check for Adobe sign in button visibility
magento/adobe-stock-integration pull request #968
Opened 2020-02-18 18:09 UTC by drpayyne

### Description

Added ACL check for rendering 'Sign In' button template content

### Fixed Issues
1. magento/adobe-stock-integration#966: Adobe Stock Sign In link is shown even if user does not have IMS login permissions

### Manual testing scenarios 
1. Sign in to Admin panel
2. Disable enhanced media gallery
3. Verify 'Sign In' button is visible in Adobe Stock panel for admin user _with_ permissions for Adobe IMS
4. Remove permission for Adobe IMS for admin user
5. Verify 'Sign In' button is not visible in Adobe Stock panel for admin user _without_ permissions for Adobe IMS

2020-02-19 07:14 UTC, drpayyne commented
@sivaschenko @filmaj, this would need an MFTF test coverage, right?

2020-02-20 21:43 UTC, sivaschenko requested changes
Thanks for the pull request @drpayyne ! I think it would be better to keep the block implementation and permission management separately and correct the `aclResource` in `AdobeStockImageAdminUi/view/adminhtml/layout/cms_wysiwyg_images_index.xml`

Yes, this change requires an MFTF test to cover it

2020-02-25 04:04 UTC, drpayyne commented
Hi @sivaschenko, please review when you can. Thanks!

2020-02-25 14:56 UTC, sivaschenko approved these changes

2020-02-25 14:57 UTC, merged