Implement HTTP action interface in controllers
magento/adobe-stock-integration pull request #976
Opened 2020-02-22 06:15 UTC by konarshankar07

### Description (*)

This PR will enhance the security for the controllers. As per Magento Architecure, To improve security and logistics we need to allow limiting Actions to processing only requests with certain HTTP methods and add those limitations to as many existing Actions as possible. There are many vulnerabilities caused by actions processing both GET and POST requests and thus allowing bypassing security validations like form key validation. Also limiting actions to processing only requests with certain methods would serve as self-documentation for Action classes and improve consistency of server side for client code and functional tests.
More Information:- https://github.com/magento/architecture/blob/514952e8883234140071ec70f3b696d8267d52d0/design-documents/allowed-http-methods-for-actions.md

2020-02-22 21:38 UTC, sivaschenko requested changes
Hi @konarshankar07 thanks for the great initiative! This pull request provided an opportunity to review the requests we are using for specific actions and I think we have to perform the requests that do not change the system using the GET method, it would be good to update such calls accordingly. Please see my comments

2020-02-22 21:38 UTC, sivaschenko commented on AdobeIms/Controller/Adminhtml/User/Profile.php
> +class Profile extends Action implements HttpPostActionInterface
This controller is used to retrieve data only, let's make it implement the Get interface and change the call in `.modman/adobe-stock-integration/AdobeIms/view/adminhtml/web/js/signIn.js`

2020-02-22 21:38 UTC, sivaschenko commented on AdobeStockAdminUi/Controller/Adminhtml/System/Config/TestConnection.php
> +class TestConnection extends Action implements HttpPostActionInterface
This operation does not change the system - let's change it to Get and update connection.js as well

2020-02-22 21:38 UTC, sivaschenko commented on AdobeStockImageAdminUi/Controller/Adminhtml/License/Confirmation.php
> +class Confirmation extends Action implements HttpPostActionInterface
I'd change this operation to Get as well

2020-02-22 21:38 UTC, sivaschenko commented on AdobeStockImageAdminUi/Controller/Adminhtml/License/Quota.php
> +class Quota extends Action implements HttpPostActionInterface
GET request would suite this operation better

2020-02-22 21:38 UTC, sivaschenko commented on MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
> +class GetTree extends Action implements HttpPostActionInterface
GET

2020-02-23 05:16 UTC, konarshankar07 commented
Hello @sivaschenko ,
Thank you for the code review and I think logout request also needs to change to GET request. Let me know your thoughts

2020-02-23 20:50 UTC, sivaschenko commented
@konarshankar07 thanks for the updates! The logout request does change a system state (admin is no longer logged in, tokens cleared from db) so it should be a POST request

2020-02-23 20:57 UTC, sivaschenko requested changes
Thanks for the updates @konarshankar07 ! Can you please also remove the form key from the requests changed to GET

2020-02-23 20:57 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
>                  data: {
form_key is not required for GET requests

2020-02-23 20:57 UTC, sivaschenko commented on AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
>                      'form_key': window.FORM_KEY
form_key is not required for GET requests

2020-02-23 20:57 UTC, sivaschenko commented on MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
>                      'form_key': FORM_KEY
form_key is not required for GET requests

2020-02-23 20:57 UTC, sivaschenko commented on AdobeIms/view/adminhtml/web/js/signIn.js
>                  data: {
form_key is not required for GET requests

2020-02-25 15:15 UTC, sivaschenko submitted a review, later dismissed

2020-02-25 20:17 UTC, sivaschenko approved these changes

2020-02-25 20:17 UTC, merged