Virtual type introduced for the option provider
magento/adobe-stock-integration pull request #987
Opened 2020-02-26 08:18 UTC by konarshankar07

### Description (*)

This PR will introduce virtualType for the `Magento\Framework\Data\OptionSourceInterface`.

2020-03-18 14:19 UTC, sivaschenko requested changes
Hi @konarshankar07 thanks for the pull request! As we discussed on the public meeting it's possible to use a class configuration similar to approach implemented for `\Magento\AdobeStockClient\Model\SearchParametersProvider\SimpleFilters`. Virtual type is not necessary in this case

2020-03-18 18:21 UTC, konarshankar07 commented
Hello @sivaschenko ...
Yes, I understood that but I still have a confusion but may be I'm wrong. If we use the real class then we still need to create separate class for each filter and repeating same code for each filter is not making sense to me. Correct me if I'm wrong
Thanks

2020-03-29 23:06 UTC, sivaschenko commented
@konarshankar07 you will be able to extend arguments di.xml configuration for the real class the same way as for virtual class

2020-03-31 18:08 UTC, sivaschenko commented on AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ContentType/Options.php
> +    public function toOptionArray()
```suggestion
    public function toOptionArray(): array
```

2020-03-31 18:09 UTC, sivaschenko submitted a review, later dismissed

2020-04-01 13:19 UTC, sivaschenko commented on AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ContentType/Options.php
> +    protected $_options = [];
```suggestion
    private $_options = [];
```

2020-04-01 13:21 UTC, sivaschenko approved these changes

2020-04-01 15:23 UTC, merged