#18 Implement search filter for the color attribute
magento/adobe-stock-integration pull request #99
Opened 2019-06-14 01:05 UTC by diazwatson

### Description (*)

#18 Although it seems to be working there are two things I am not happy about it:
![Screenshot 2019-06-14 at 01 51 16](https://user-images.githubusercontent.com/1080386/59476434-929c0a00-8e48-11e9-93f4-6a2b8be5f40b.png)
![Screenshot 2019-06-14 at 01 51 33](https://user-images.githubusercontent.com/1080386/59476439-9af44500-8e48-11e9-8ee1-d8883ee52ab2.png)

- Rules defined in `Magento_Ui:etc/ui_configuration.xsd` do not allow a colorPicker component to be added inside a listing component (should we extend `ui_configuration.xsd` to include this type of configuration?).
- As you can see, the label of the filter is aligned to the right, this is due to the class automatically added to the component (`admin__field-label`). the right class should be `admin__form-field-label`

I am going to continue reviewing this to see if I can fix the issues or there is a better way to implement this filter.

2019-06-16 22:57 UTC, diazwatson commented
Hey Guys, I have refactored to use the template component class approach instead of the color picker but for some reason the label doesn't show. Has anyone seen similar issue with a Ui Component  before?

2019-06-20 13:40 UTC, larsroettig requested changes

2019-06-20 13:40 UTC, larsroettig commented on AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
> +<?php
Please Use **strict_type** 

```php
<?php
/**
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);
```

2019-06-20 13:40 UTC, larsroettig commented on AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
> +    const NAME = 'filter_input';
why do you add their const for one-time usage? Usually, we have const only interfaces`

2019-06-20 13:40 UTC, larsroettig commented on AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
> +    protected $wrappedComponent;
OPTIONAL: you should use private there to enforce setter and getter

2019-06-20 13:40 UTC, larsroettig commented on AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
> +    public function __construct(
Missing doc block static should fail

2019-06-20 13:40 UTC, larsroettig commented on AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
> +    private function initColorPickerConfig()
Missing docblock what do

2019-06-22 10:53 UTC, diazwatson commented
Hi @larsroettig 
I believe all changes you requested are now covered, could you please review and let me know if any?

Cheers

2019-06-22 13:32 UTC, sivaschenko approved these changes

2019-06-23 12:08 UTC, larsroettig approved these changes

2019-06-24 21:55 UTC, sidolov approved these changes

2019-06-24 21:55 UTC, merged